# Generated by Django 5.2.17 on 2026-10-04 15:38

import apps.catalog.validators
import apps.loop.models.items
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('closet', '0001_initial'),
        ('orders', '0002_order_loyalty_points_order_promotion_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('resale', 'Resale'), ('trade_in', 'Trade-in'), ('recycle', 'Recycle')], help_text='The path this item enters: resale, trade-in or recycling.', max_length=16, verbose_name='loop type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('listed', 'Listed'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('trade_in_accepted', 'Trade-in accepted'), ('trade_in_completed', 'Trade-in completed'), ('recycle_accepted', 'Recycle accepted'), ('recycle_completed', 'Recycle completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24, verbose_name='status')),
                ('condition', models.CharField(choices=[('new_with_tags', 'New with tags'), ('like_new', 'Like new'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], help_text='Seller-stated condition; treated as unverified until reviewed.', max_length=16, verbose_name='condition')),
                ('condition_notes', models.TextField(blank=True, help_text='Plain-text seller notes (worn twice, stitching mark, ...).', verbose_name='condition notes')),
                ('title', models.CharField(blank=True, help_text='Resale title; falls back to the catalogue product name.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Plain-text resale description. No HTML.', verbose_name='description')),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, help_text='Seller-proposed price. Validated against the configured bounds.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='asking price')),
                ('authenticity_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text="Staff-controlled. Unverified means 'not checked', not 'fake'.", max_length=16, verbose_name='authenticity status')),
                ('moderation_note', models.CharField(blank=True, help_text='Internal note. Never rendered in customer-facing templates.', max_length=300, verbose_name='moderation note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='listed at')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='sold at')),
                ('closet_item', models.ForeignKey(blank=True, help_text='The wardrobe row for this physical unit, when it is in the closet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loop_items', to='closet.closetitem', verbose_name='closet item')),
                ('order_item', models.ForeignKey(blank=True, help_text='The delivered order line this unit came from, when known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loop_items', to='orders.orderitem', verbose_name='order line')),
                ('product', models.ForeignKey(blank=True, help_text="The garment's catalogue row; resolves all display details.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loop_items', to='catalog.product', verbose_name='product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_items', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('variant', models.ForeignKey(blank=True, help_text='The specific SKU (colour/size) being circulated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loop_items', to='catalog.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'loop item',
                'verbose_name_plural': 'loop items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoopItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(help_text='JPEG, PNG or WebP, within the catalogue image limits.', upload_to=apps.loop.models.items.loop_image_upload_to, validators=[apps.catalog.validators.validate_catalog_image], verbose_name='image')),
                ('kind', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('label', 'Label'), ('detail', 'Condition detail'), ('additional', 'Additional')], default='front', help_text='What the photo shows. Determines its place in the gallery.', max_length=16, verbose_name='kind')),
                ('alt_text', models.CharField(help_text='Describe the photo for screen readers.', max_length=200, verbose_name='alt text')),
                ('position', models.PositiveIntegerField(default=0, help_text='Gallery order. Lower numbers come first.', verbose_name='position')),
                ('loop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loop.loopitem', verbose_name='loop item')),
            ],
            options={
                'verbose_name': 'loop item image',
                'verbose_name_plural': 'loop item images',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RecycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=16, verbose_name='status')),
                ('instructions', models.TextField(blank=True, help_text='Plain-text drop-off or packaging notes for the customer.', verbose_name='instructions')),
                ('material_category', models.CharField(blank=True, help_text='Material the item was sorted into. Set at processing.', max_length=120, verbose_name='material category')),
                ('impact', models.JSONField(blank=True, default=dict, help_text='Staff-written facts only (e.g. sorting outcome). No fabricated claims.', verbose_name='environmental impact')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('loop_item', models.OneToOneField(help_text='The recycling item. One request per item.', on_delete=django.db.models.deletion.PROTECT, related_name='recycle_request', to='loop.loopitem', verbose_name='loop item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recycle_requests', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'recycle request',
                'verbose_name_plural': 'recycle requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(help_text='Public URL handle. Derived, then frozen.', max_length=200, unique=True, verbose_name='slug')),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='The seller-proposed price, validated at submission.', max_digits=10, verbose_name='asking price')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending_review', max_length=16, verbose_name='status')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='listed at')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='sold at')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expired at')),
                ('loop_item', models.OneToOneField(help_text='The resale item this listing sells. One listing per item.', on_delete=django.db.models.deletion.PROTECT, related_name='resale_listing', to='loop.loopitem', verbose_name='loop item')),
                ('seller', models.ForeignKey(help_text='Always the verified owner; never client-supplied.', on_delete=django.db.models.deletion.PROTECT, related_name='resale_listings', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'resale listing',
                'verbose_name_plural': 'resale listings',
                'ordering': ('-listed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('offered', 'Offer made'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('received', 'Received'), ('inspected', 'Inspected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=16, verbose_name='status')),
                ('estimated_credit', models.DecimalField(blank=True, decimal_places=2, help_text='Policy estimate shown to the customer. Not a promise.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='estimated credit')),
                ('final_credit', models.DecimalField(blank=True, decimal_places=2, help_text='Reviewer-set credit awarded on completion.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='final credit')),
                ('reviewer_note', models.CharField(blank=True, help_text='Internal note. Never rendered in customer templates.', max_length=300, verbose_name='reviewer note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('loop_item', models.OneToOneField(help_text='The trade-in item. One request per item.', on_delete=django.db.models.deletion.PROTECT, related_name='trade_in_request', to='loop.loopitem', verbose_name='loop item')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_in_requests', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'trade-in request',
                'verbose_name_plural': 'trade-in requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoopCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Sign lives in the status, not the amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount')),
                ('reference', models.CharField(help_text="Idempotency key, e.g. 'trade-in:42'.", max_length=64, unique=True, verbose_name='reference')),
                ('status', models.CharField(choices=[('awarded', 'Awarded'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='awarded', max_length=16, verbose_name='status')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the credit was awarded.', verbose_name='awarded at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Blank means the credit does not expire.', null=True, verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_credits', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('loop_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='loop.loopitem', verbose_name='loop item')),
                ('trade_in_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='loop.tradeinrequest', verbose_name='trade-in request')),
            ],
            options={
                'verbose_name': 'loop credit',
                'verbose_name_plural': 'loop credits',
                'ordering': ('-awarded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='loopitem',
            index=models.Index(fields=['user', 'status'], name='loop_item_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loopitem',
            index=models.Index(fields=['user', 'type'], name='loop_item_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='loopitem',
            index=models.Index(fields=['product', 'status'], name='loop_item_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loopitem',
            index=models.Index(fields=['-created_at'], name='loop_item_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='loopitem',
            constraint=models.CheckConstraint(condition=models.Q(('asking_price__isnull', True), ('asking_price__gte', 0), _connector='OR'), name='loop_item_asking_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loopitem',
            constraint=models.UniqueConstraint(condition=models.Q(('closet_item__isnull', False), models.Q(('status__in', ('rejected', 'sold', 'cancelled', 'trade_in_completed', 'recycle_completed')), _negated=True)), fields=('closet_item',), name='loop_item_one_active_per_closet_item'),
        ),
        migrations.AddConstraint(
            model_name='loopitem',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item__isnull', False), ('closet_item__isnull', True), models.Q(('status__in', ('rejected', 'sold', 'cancelled', 'trade_in_completed', 'recycle_completed')), _negated=True)), fields=('order_item',), name='loop_item_one_active_per_order_item'),
        ),
        migrations.AddIndex(
            model_name='loopitemimage',
            index=models.Index(fields=['loop_item', 'position'], name='loop_image_item_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclerequest',
            index=models.Index(fields=['user', 'status'], name='loop_recycle_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclerequest',
            index=models.Index(fields=['status', '-created_at'], name='loop_recycle_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclerequest',
            index=models.Index(fields=['loop_item'], name='loop_recycle_item_idx'),
        ),
        migrations.AddIndex(
            model_name='resalelisting',
            index=models.Index(fields=['status', '-listed_at'], name='loop_listing_status_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='resalelisting',
            index=models.Index(fields=['seller', 'status'], name='loop_listing_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resalelisting',
            index=models.Index(fields=['loop_item'], name='loop_listing_item_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['user', 'status'], name='loop_tradein_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['status', '-created_at'], name='loop_tradein_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['loop_item'], name='loop_tradein_item_idx'),
        ),
        migrations.AddIndex(
            model_name='loopcredit',
            index=models.Index(fields=['user', 'status'], name='loop_credit_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loopcredit',
            index=models.Index(fields=['status', 'expires_at'], name='loop_credit_status_expires_idx'),
        ),
    ]
