# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_cat_prod_featured_idx"),
        ("closet", "0001_initial"),
        ("loop", "0001_initial"),
        ("orders", "0002_order_loyalty_points_order_promotion_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loopitem",
            index=models.Index(fields=["type", "-created_at"], name="loop_item_type_created_idx"),
        ),
    ]
