# Generated by Django 5.2.17 on 2026-10-03 21:06

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_deactivated_at_user_email_verified_at_and_more"),
        ("catalog", "0001_initial"),
        ("shop", "0004_alter_checkoutsession_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        help_text="Public, non-sequential handle: FW-<date>-<random>.",
                        max_length=32,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217 code, frozen from the cart at order creation.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="subtotal"),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="shipping amount"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Reserved for promotions; always zero in Phase 6.",
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Reserved for tax calculation; always zero in Phase 6.",
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="total"),
                ),
                ("shipping_code", models.CharField(max_length=32, verbose_name="shipping method")),
                (
                    "shipping_name",
                    models.CharField(max_length=64, verbose_name="shipping method name"),
                ),
                (
                    "shipping_estimate",
                    models.CharField(blank=True, max_length=64, verbose_name="delivery estimate"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "checkout",
                    models.OneToOneField(
                        help_text="The validated session this order was built from; also its idempotency key.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="shop.checkoutsession",
                        verbose_name="checkout",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="full name")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="phone")),
                ("line1", models.CharField(max_length=255, verbose_name="address line 1")),
                (
                    "line2",
                    models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
                ),
                ("city", models.CharField(max_length=120, verbose_name="city")),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="region / state"),
                ),
                ("postal_code", models.CharField(max_length=20, verbose_name="postal code")),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2.", max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="accounts.address",
                        verbose_name="address book entry",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order address",
                "verbose_name_plural": "order addresses",
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Order created"),
                            ("payment_pending", "Payment initiated"),
                            ("payment_succeeded", "Payment succeeded"),
                            ("payment_failed", "Payment failed"),
                            ("payment_cancelled", "Payment cancelled"),
                            ("status_changed", "Status changed"),
                            ("stock_reserved", "Stock reserved"),
                            ("stock_consumed", "Stock consumed"),
                            ("stock_released", "Stock released"),
                            ("shipment_created", "Shipment created"),
                            ("shipment_updated", "Shipment updated"),
                            ("cancelled_by_customer", "Cancelled by customer"),
                            ("note", "Note"),
                        ],
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="note")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Small, non-sensitive facts.",
                        verbose_name="metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member or customer behind the event; null for system events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order event",
                "verbose_name_plural": "order events",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=64, verbose_name="SKU")),
                ("product_name", models.CharField(max_length=200, verbose_name="product")),
                (
                    "option_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Black / M'.",
                        max_length=200,
                        verbose_name="option",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="unit price"),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="line total"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="Shipping method code frozen from the order.",
                        max_length=32,
                        verbose_name="method",
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=64, verbose_name="carrier")),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=64, verbose_name="tracking number"),
                ),
                (
                    "estimated_delivery",
                    models.DateField(blank=True, null=True, verbose_name="estimated delivery"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                        verbose_name="event type",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="note")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.shipment",
                        verbose_name="shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment event",
                "verbose_name_plural": "shipment events",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "variant"), name="orders_one_line_per_variant"
            ),
        ),
    ]
