# Generated by Django 5.2.17 on 2026-10-04 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Points redeemed on this order; already folded into discount_amount.', verbose_name='FLASH Points redeemed'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, default='', help_text='Normalised code the discount came from; for support and reporting.', max_length=32, verbose_name='promotion code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Promotion plus FLASH Points discount, frozen at order creation (Phase 7).', max_digits=10, verbose_name='discount amount'),
        ),
    ]
