# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_loyalty_points_order_promotion_code_and_more"),
        ("shop", "0005_checkoutsession_loyalty_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-created_at"], name="orders_order_created_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["-created_at"], name="orders_shipment_created_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status", "-created_at"], name="orders_shipment_status_idx"),
        ),
    ]
