# Generated by Django 5.2.17 on 2026-10-06 12:08

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_cat_prod_featured_idx"),
        ("orders", "0003_order_orders_order_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        help_text="Public handle: RET-<date>-<random>.",
                        max_length=32,
                        unique=True,
                        verbose_name="return number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("received", "Received"),
                            ("inspected", "Inspected"),
                            ("refunded", "Refunded"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "return_type",
                    models.CharField(
                        choices=[("refund", "Refund"), ("exchange", "Exchange")],
                        default="refund",
                        max_length=16,
                        verbose_name="return type",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("size_fit", "Size or fit issue"),
                            ("defective", "Defective or damaged"),
                            ("not_as_described", "Item not as described"),
                            ("changed_mind", "Changed mind"),
                            ("wrong_item", "Wrong item received"),
                            ("other", "Other"),
                        ],
                        default="size_fit",
                        max_length=32,
                        verbose_name="primary reason",
                    ),
                ),
                ("customer_note", models.TextField(blank=True, verbose_name="customer note")),
                ("staff_note", models.TextField(blank=True, verbose_name="staff note")),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="return tracking number"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="approved at"),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="received at"),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="inspected at"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="refunded at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="rejected at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "return request",
                "verbose_name_plural": "return requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="requested quantity")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("size_fit", "Size or fit issue"),
                            ("defective", "Defective or damaged"),
                            ("not_as_described", "Item not as described"),
                            ("changed_mind", "Changed mind"),
                            ("wrong_item", "Wrong item received"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="reason",
                    ),
                ),
                (
                    "customer_note",
                    models.CharField(blank=True, max_length=300, verbose_name="customer note"),
                ),
                (
                    "price_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Replacement variant total minus original line price.",
                        max_digits=10,
                        verbose_name="price difference",
                    ),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="received quantity"),
                ),
                (
                    "accepted_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="accepted quantity"),
                ),
                (
                    "rejected_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="rejected quantity"),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unopened", "Unopened / Original packaging"),
                            ("like_new", "Like new / Unworn"),
                            ("opened_unused", "Opened but unused"),
                            ("damaged_customer", "Customer damaged"),
                            ("defective", "Defective item"),
                            ("worn", "Worn or washed"),
                        ],
                        max_length=32,
                        verbose_name="condition",
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True, verbose_name="inspection notes")),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="refund amount",
                    ),
                ),
                ("is_restocked", models.BooleanField(default=False, verbose_name="is restocked")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                        verbose_name="order item",
                    ),
                ),
                (
                    "replacement_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_return_items",
                        to="catalog.productvariant",
                        verbose_name="replacement variant",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.returnrequest",
                        verbose_name="return request",
                    ),
                ),
            ],
            options={
                "verbose_name": "return item",
                "verbose_name_plural": "return items",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="ReturnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=32, verbose_name="event type")),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="note")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.returnrequest",
                        verbose_name="return request",
                    ),
                ),
            ],
            options={
                "verbose_name": "return event",
                "verbose_name_plural": "return events",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["order", "-created_at"], name="orders_retu_order_i_bab601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_retu_user_id_6e7e2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_retu_status_3b5dcd_idx"
            ),
        ),
    ]
