# Generated by Django 5.2.17 on 2026-10-03 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the customer requests account closure.",
                null=True,
                verbose_name="deactivated at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Left empty until the address is proven; never guessed from the signup form.",
                null=True,
                verbose_name="email verified at",
            ),
        ),
        migrations.CreateModel(
            name="AccountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_digest",
                    models.CharField(
                        blank=True,
                        help_text="Salted hash of the account email, so an event stays traceable after anonymisation without storing the address.",
                        max_length=64,
                        verbose_name="email digest",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("email_verification_sent", "Email verification sent"),
                            ("email_verified", "Email verified"),
                            ("password_reset_requested", "Password reset requested"),
                            ("password_changed", "Password changed"),
                            ("profile_updated", "Profile updated"),
                            ("address_created", "Address created"),
                            ("address_updated", "Address updated"),
                            ("address_deleted", "Address deleted"),
                            ("default_address_changed", "Default address changed"),
                            ("account_deactivated", "Account deactivated"),
                        ],
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        default="web",
                        help_text="Surface the event came from, e.g. web or api.",
                        max_length=20,
                        verbose_name="channel",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "ip_digest",
                    models.CharField(
                        blank=True,
                        help_text="Salted hash of the client address. Raw addresses are never stored.",
                        max_length=64,
                        verbose_name="IP digest",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "account event",
                "verbose_name_plural": "account events",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="acc_evt_user_created_idx"),
                    models.Index(
                        fields=["event_type", "-created_at"], name="acc_evt_type_created_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="full name")),
                ("phone", models.CharField(max_length=32, verbose_name="phone")),
                ("line1", models.CharField(max_length=200, verbose_name="address line 1")),
                (
                    "line2",
                    models.CharField(blank=True, max_length=200, verbose_name="address line 2"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="district / state / region"),
                ),
                ("postal_code", models.CharField(max_length=20, verbose_name="postal code")),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code, e.g. DE, GB, US.",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("billing", "Billing"),
                            ("both", "Shipping and billing"),
                        ],
                        default="shipping",
                        max_length=10,
                        verbose_name="address type",
                    ),
                ),
                (
                    "is_default_shipping",
                    models.BooleanField(default=False, verbose_name="default shipping address"),
                ),
                (
                    "is_default_billing",
                    models.BooleanField(default=False, verbose_name="default billing address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ("-is_default_shipping", "-is_default_billing", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_shipping", True)),
                        fields=("user",),
                        name="accounts_address_one_default_shipping_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_billing", True)),
                        fields=("user",),
                        name="accounts_address_one_default_billing_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("country__regex", "^[A-Z]{2}$")),
                        name="accounts_address_country_iso3166",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_default_billing", True), _negated=True),
                            ("address_type__in", ["billing", "both"]),
                            _connector="OR",
                        ),
                        name="accounts_address_billing_default_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Square image. PNG, JPEG or WebP, within the configured size limit.",
                        upload_to="avatars/",
                        verbose_name="avatar",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="phone")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en",
                        help_text="BCP 47 language tag used for storefront copy.",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 code. A display preference only -- never used for money maths.",
                        max_length=3,
                        verbose_name="preferred currency",
                    ),
                ),
                (
                    "marketing_email_opt_in",
                    models.BooleanField(default=False, verbose_name="marketing email opt-in"),
                ),
                (
                    "marketing_sms_opt_in",
                    models.BooleanField(default=False, verbose_name="marketing SMS opt-in"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "ordering": ("user__email",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("preferred_currency__regex", "^[A-Z]{3}$")),
                        name="accounts_profile_currency_iso4217",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("marketing_sms_opt_in", False), ("phone__gt", ""), _connector="OR"
                        ),
                        name="accounts_profile_sms_opt_in_requires_phone",
                    ),
                ],
            },
        ),
    ]
