# Generated by Django 5.2.17 on 2026-10-05 12:30

from django.db import migrations, models

import apps.accounts.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_deactivated_at_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Square image. PNG, JPEG or WebP, within the configured size limit.",
                upload_to="avatars/",
                validators=[apps.accounts.validators.validate_avatar],
                verbose_name="avatar",
            ),
        ),
    ]
