# Generated by Django 5.2.17 on 2026-10-05 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
    ]
