# Generated by Django 5.2.17 on 2026-10-05 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_cat_prod_featured_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashDNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "styles",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list from: Minimal, Streetwear, Smart casual, Formal, Vintage, Sporty, Oversized, Classic.",
                        max_length=64,
                        verbose_name="preferred styles",
                    ),
                ),
                (
                    "preferred_categories",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tops", "Tops"),
                            ("bottoms", "Bottoms"),
                            ("outerwear", "Outerwear"),
                            ("dresses", "Dresses"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                        ],
                        help_text="Wardrobe categories the customer reaches for most. From the closet taxonomy.",
                        max_length=32,
                        verbose_name="preferred categories",
                    ),
                ),
                (
                    "preferred_occasions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual"),
                            ("office", "Office"),
                            ("university", "University"),
                            ("date", "Date"),
                            ("party", "Party"),
                            ("wedding", "Wedding"),
                            ("travel", "Travel"),
                            ("formal", "Formal"),
                        ],
                        help_text="Events where the customer wants to look appropriate.",
                        max_length=32,
                        verbose_name="preferred occasions",
                    ),
                ),
                (
                    "preferred_seasons",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_season", "All season"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        help_text="Time of year the customer prefers.",
                        max_length=32,
                        verbose_name="preferred seasons",
                    ),
                ),
                (
                    "preferred_price_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_25", "Under $25"),
                            ("under_50", "Under $50"),
                            ("under_100", "Under $100"),
                            ("under_150", "Under $150"),
                            ("above_150", "Above $150"),
                        ],
                        help_text="Upper bound only. The customer's typical spending limit.",
                        max_length=20,
                        verbose_name="preferred price range",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        blank=True,
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        help_text="How confident the customer is in their own style sense. Used by the AI stylist to weight explicit preferences.",
                        max_length=16,
                        verbose_name="style confidence",
                    ),
                ),
                (
                    "fashion_goal",
                    models.CharField(
                        blank=True,
                        help_text="What the customer is working towards, e.g. Build a capsule wardrobe, Dress more professionally, Experiment with color.",
                        max_length=120,
                        verbose_name="fashion goal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "disliked_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Colors the customer actively avoids. Rows from the catalogue colour system. Take precedence over favourite colours when both are set.",
                        related_name="disliked_dna",
                        to="catalog.color",
                        verbose_name="disliked colors",
                    ),
                ),
                (
                    "favorite_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Colors the customer loves. Rows from the catalogue colour system.",
                        related_name="favorite_dna",
                        to="catalog.color",
                        verbose_name="favorite colors",
                    ),
                ),
                (
                    "preferred_brands",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Brands the customer tends to choose. From the catalogue.",
                        to="catalog.brand",
                        verbose_name="preferred brands",
                    ),
                ),
                (
                    "preferred_fits",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Structured fit labels from the catalogue (e.g. Slim, Relaxed, Oversized). These are queryable, unlike free-text fit notes.",
                        to="catalog.fit",
                        verbose_name="preferred fits",
                    ),
                ),
                (
                    "preferred_materials",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fabric/composition labels from the catalogue. Filterable, not free text.",
                        to="catalog.material",
                        verbose_name="preferred materials",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="CASCADE: DNA is private user data and leaves with the account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_dna",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "FLASH DNA",
                "verbose_name_plural": "FLASH DNA",
                "ordering": ("-updated_at",),
            },
        ),
    ]
