# Generated by Django 5.2.17 on 2026-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashdna",
            name="style_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("streetwear", "Streetwear"),
                    ("smart_casual", "Smart casual"),
                    ("formal", "Formal"),
                    ("trendy", "Trendy"),
                    ("classic", "Classic"),
                    ("athleisure", "Athleisure"),
                ],
                help_text="Optional single style direction (Minimal, Streetwear, ...). Additive: it weights generation and recommendations without touching the preferred-styles list above.",
                max_length=20,
                verbose_name="style goal",
            ),
        ),
    ]
