"""FLASH Support & Customer Care data model (Phase 15).

Four rows, three ideas:

* :class:`SupportTicket` -- one conversation about one problem. ``status`` is a controlled
  state machine (:attr:`SupportTicket.ALLOWED_TRANSITIONS`) that both sides drive through
  :mod:`apps.support.services.tickets`; ``priority`` is agent-set only; the numbered handle
  (``FW-2026-000123``) is generated by the model from the row's own primary key, so two
  concurrent inserts can never mint the same number and no separate counter table exists.
* :class:`SupportMessage` -- the transcript. ``author_type`` says who wrote it and
  ``is_internal`` marks agent-only notes; a database constraint makes the combination
  "customer + internal" impossible, so a serializer bug cannot leak a private note as public
  or let a customer write one. Messages are append-only -- there is no edit path above this
  model, which is what makes the transcript admissible as a record of what was said.
* :class:`SupportAttachment` -- evidence on a message, stored outside ``MEDIA_ROOT`` with no
  public URL (see :mod:`apps.support.storage`).
* :class:`SupportTicketEvent` -- append-only audit. Every state change writes exactly one
  row here, so a ticket's history is reconstructable without trusting any log line.

The ticket *references* other domains (order, payment, shipment, product, review, loop item,
quest) with nullable foreign keys rather than copies: support points at the authoritative row
and never writes to it. ``creator_post_id`` is a bare integer because the creator app is not
in ``INSTALLED_APPS`` -- a foreign key to an app that is not installed cannot migrate.
"""

from __future__ import annotations

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.catalog.models.base import TimestampedModel
from apps.support.storage import PrivateAttachmentStorage

__all__ = ["SupportAttachment", "SupportMessage", "SupportTicket", "SupportTicketEvent"]

# A nested ``class Meta`` body cannot see names defined in the enclosing class body (Python
# resolves them as local/global, not as enclosing-class), so the check constraints need the
# choice values spelled out here. A test asserts these stay identical to the TextChoices.
_STATUS_VALUES = (
    "open",
    "in_progress",
    "waiting_for_customer",
    "waiting_internal",
    "escalated",
    "resolved",
    "closed",
)
_PRIORITY_VALUES = ("low", "normal", "high", "urgent")
_AUTHOR_TYPE_VALUES = ("customer", "agent", "system")


class SupportTicket(TimestampedModel):
    """One customer problem and everything the desk did about it."""

    class Status(models.TextChoices):
        OPEN = "open", _("Open")
        IN_PROGRESS = "in_progress", _("In progress")
        WAITING_FOR_CUSTOMER = "waiting_for_customer", _("Waiting for customer")
        WAITING_INTERNAL = "waiting_internal", _("Waiting on internal team")
        ESCALATED = "escalated", _("Escalated")
        RESOLVED = "resolved", _("Resolved")
        CLOSED = "closed", _("Closed")

    class Category(models.TextChoices):
        ORDER = "order", _("Order")
        PAYMENT = "payment", _("Payment")
        DELIVERY = "delivery", _("Delivery")
        RETURN = "return", _("Return")
        REFUND = "refund", _("Refund")
        PRODUCT = "product", _("Product")
        ACCOUNT = "account", _("Account")
        LOYALTY = "loyalty", _("FLASH Points")
        PROMOTION = "promotion", _("Promotion")
        FLASH_DNA = "flash_dna", _("FLASH DNA")
        FLASH_CLOSET = "flash_closet", _("FLASH Closet")
        CREATOR = "creator", _("Creator")
        FLASH_LOOP = "flash_loop", _("FLASH Loop")
        FLASH_DROP = "flash_drop", _("FLASH Drop")
        QUEST = "quest", _("Quest")
        OTHER = "other", _("Other")

    class Priority(models.TextChoices):
        LOW = "low", _("Low")
        NORMAL = "normal", _("Normal")
        HIGH = "high", _("High")
        URGENT = "urgent", _("Urgent")

    class Source(models.TextChoices):
        WEB = "web", _("Web")
        API = "api", _("API")
        SYSTEM = "system", _("System")
        ADMIN = "admin", _("Admin")

    # Customer-writable targets. Everything else on the graph is agent-only, which is how
    # "the customer may close their own ticket but cannot resolve or escalate it" is
    # expressed in one place instead of per-view.
    CUSTOMER_TARGETS = frozenset({Status.IN_PROGRESS, Status.CLOSED})

    ALLOWED_TRANSITIONS: dict[str, tuple[str, ...]] = {
        Status.OPEN: (
            Status.IN_PROGRESS,
            Status.WAITING_FOR_CUSTOMER,
            Status.WAITING_INTERNAL,
            Status.ESCALATED,
            Status.RESOLVED,
            Status.CLOSED,
        ),
        Status.IN_PROGRESS: (
            Status.WAITING_FOR_CUSTOMER,
            Status.WAITING_INTERNAL,
            Status.ESCALATED,
            Status.RESOLVED,
            Status.OPEN,
            Status.CLOSED,
        ),
        Status.WAITING_FOR_CUSTOMER: (
            Status.IN_PROGRESS,
            Status.ESCALATED,
            Status.RESOLVED,
            Status.CLOSED,
        ),
        Status.WAITING_INTERNAL: (
            Status.IN_PROGRESS,
            Status.WAITING_FOR_CUSTOMER,
            Status.ESCALATED,
            Status.RESOLVED,
            Status.CLOSED,
        ),
        Status.ESCALATED: (
            Status.IN_PROGRESS,
            Status.WAITING_INTERNAL,
            Status.WAITING_FOR_CUSTOMER,
            Status.RESOLVED,
            Status.CLOSED,
        ),
        # RESOLVED is reversible (the customer answers), CLOSED is not: reopening a closed
        # ticket is an explicit act with its own endpoint, not a side effect of replying.
        Status.RESOLVED: (Status.CLOSED, Status.IN_PROGRESS),
        Status.CLOSED: (Status.IN_PROGRESS,),
    }

    number = models.CharField(
        _("ticket number"),
        max_length=32,
        unique=True,
        editable=False,
        blank=True,
        help_text=_("Server-generated, e.g. FW-2026-000123. Never taken from a payload."),
    )
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("customer"),
        help_text=_(
            "SET_NULL: a ticket outlives the account it belongs to, so the transcript stays "
            "auditable after anonymisation."
        ),
    )
    subject = models.CharField(_("subject"), max_length=200)
    description = models.TextField(
        _("description"),
        help_text=_("Denormalised copy of the first message, for list views."),
    )
    category = models.CharField(
        _("category"), max_length=20, choices=Category.choices, default=Category.OTHER
    )
    priority = models.CharField(
        _("priority"), max_length=10, choices=Priority.choices, default=Priority.NORMAL
    )
    status = models.CharField(
        _("status"), max_length=24, choices=Status.choices, default=Status.OPEN
    )
    source = models.CharField(
        _("source"), max_length=10, choices=Source.choices, default=Source.WEB
    )

    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        verbose_name=_("assigned to"),
    )
    assigned_at = models.DateTimeField(_("assigned at"), null=True, blank=True)
    first_response_at = models.DateTimeField(_("first response at"), null=True, blank=True)
    resolved_at = models.DateTimeField(_("resolved at"), null=True, blank=True)
    closed_at = models.DateTimeField(_("closed at"), null=True, blank=True)
    last_customer_message_at = models.DateTimeField(
        _("last customer message at"), null=True, blank=True
    )
    last_agent_message_at = models.DateTimeField(_("last agent message at"), null=True, blank=True)

    escalation_reason = models.TextField(_("escalation reason"), blank=True)
    escalation_target = models.CharField(_("escalation target"), max_length=20, blank=True)
    escalated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        verbose_name=_("escalated by"),
    )
    escalated_at = models.DateTimeField(_("escalated at"), null=True, blank=True)

    # --- references to the domains this ticket is about -------------------------------
    # All SET_NULL on purpose: a ticket is a record of a conversation, and deleting a
    # product or a review must not delete what someone was told about it.
    order = models.ForeignKey(
        "orders.Order",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("order"),
    )
    payment = models.ForeignKey(
        "payments.Payment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("payment"),
    )
    shipment = models.ForeignKey(
        "orders.Shipment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("shipment"),
    )
    product = models.ForeignKey(
        "catalog.Product",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("product"),
    )
    review = models.ForeignKey(
        "engagement.Review",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("review"),
    )
    loop_item = models.ForeignKey(
        "loop.LoopItem",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("loop item"),
    )
    quest = models.ForeignKey(
        "quests.Quest",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="support_tickets",
        verbose_name=_("quest"),
    )
    # The creator app is dormant (not in INSTALLED_APPS), so this cannot be a foreign key.
    # It is resolved at read time by apps.support.selectors.creator_post_title.
    creator_post_id = models.PositiveIntegerField(
        _("creator post id"),
        null=True,
        blank=True,
        validators=[MinValueValidator(1)],
        help_text=_("Bare id, not a foreign key: apps.creator is not installed."),
    )

    metadata = models.JSONField(_("metadata"), default=dict, blank=True)

    class Meta:
        verbose_name = _("support ticket")
        verbose_name_plural = _("support tickets")
        ordering = ("-created_at",)
        constraints = [
            models.CheckConstraint(
                condition=models.Q(status__in=_STATUS_VALUES),
                name="support_ticket_status_known",
            ),
            models.CheckConstraint(
                condition=models.Q(priority__in=_PRIORITY_VALUES),
                name="support_ticket_priority_known",
            ),
        ]
        indexes = [
            models.Index(fields=["customer", "-created_at"], name="support_ticket_cust_idx"),
            models.Index(fields=["status", "-created_at"], name="support_ticket_status_idx"),
            models.Index(fields=["assigned_to", "status"], name="support_ticket_assign_idx"),
            models.Index(fields=["category", "status"], name="support_ticket_cat_idx"),
            # The support queue's default sort and its priority filter -- both were bare.
            models.Index(fields=["-updated_at"], name="support_ticket_updated_idx"),
            models.Index(fields=["priority", "-updated_at"], name="support_ticket_prio_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.number or '(new)'} — {self.subject}"

    # -- numbering ------------------------------------------------------------------
    def save(self, *args, **kwargs):
        """Assign a human-readable number on first insert.

        The number is derived from the primary key, which only exists after the row is in,
        so the insert happens with a unique placeholder and a second save stamps the final
        value. Two rows can never collide (two rows can never share a primary key) and no
        sequence table is needed -- unlike a "count the rows" scheme, this stays correct
        when tickets are deleted or when two workers insert at once.

        A row that already carries a number (a fixture, a migration, an import) is written
        exactly as given: the guard is ``if not self.number``, so nothing re-mints it.
        """
        if not self.number:
            super().save(*args, **kwargs)
            self.number = f"FW-{timezone.now().year}-{self.pk:06d}"
            super().save(update_fields=["number"])
            return
        super().save(*args, **kwargs)

    def can_transition_to(self, target: str) -> bool:
        return target in self.ALLOWED_TRANSITIONS.get(self.status, ())

    # -- helpers --------------------------------------------------------------------
    @property
    def is_open(self) -> bool:
        return self.status not in {self.Status.RESOLVED, self.Status.CLOSED}

    @property
    def creator_post(self) -> object:
        """Resolve the dormant creator reference, or ``None`` when the app is absent."""
        if not self.creator_post_id:
            return None
        try:
            from apps.creator.models import CreatorPost
        except ImportError:
            return None
        return CreatorPost.objects.filter(pk=self.creator_post_id).first()

    @property
    def reference_labels(self) -> list[str]:
        """Human labels for whatever this ticket points at, for list and detail views."""
        labels: list[str] = []
        if self.order_id:
            labels.append(f"Order {self.order.number}")
        if self.payment_id:
            labels.append(f"Payment {self.payment.provider_reference or self.payment.pk}")
        if self.shipment_id:
            labels.append(
                f"Shipment {self.shipment.tracking_number or self.shipment.get_status_display()}"
            )
        if self.product_id:
            labels.append(f"Product {self.product.name}")
        if self.review_id:
            labels.append(f"Review #{self.review_id}")
        if self.loop_item_id:
            labels.append(f"Loop item #{self.loop_item_id}")
        if self.quest_id:
            labels.append(f"Quest {self.quest.name}")
        if self.creator_post_id:
            labels.append(f"Creator post #{self.creator_post_id}")
        return labels


class SupportMessage(TimestampedModel):
    """One entry in a ticket's transcript. Append-only above this layer."""

    class AuthorType(models.TextChoices):
        CUSTOMER = "customer", _("Customer")
        AGENT = "agent", _("Agent")
        SYSTEM = "system", _("System")

    ticket = models.ForeignKey(
        SupportTicket,
        on_delete=models.CASCADE,
        related_name="messages",
        verbose_name=_("ticket"),
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        verbose_name=_("author"),
        help_text=_("NULL for SYSTEM entries (the platform writing to the transcript)."),
    )
    author_type = models.CharField(
        _("author type"), max_length=10, choices=AuthorType.choices, default=AuthorType.CUSTOMER
    )
    body = models.TextField(_("body"))
    is_internal = models.BooleanField(
        _("internal"),
        default=False,
        help_text=_("Agent-only. Never rendered to, or emailed to, the customer."),
    )

    class Meta:
        verbose_name = _("support message")
        verbose_name_plural = _("support messages")
        ordering = ("created_at", "pk")
        constraints = [
            models.CheckConstraint(
                condition=~(models.Q(author_type="customer") & models.Q(is_internal=True)),
                name="support_message_customer_not_internal",
            ),
            models.CheckConstraint(
                condition=models.Q(author_type__in=_AUTHOR_TYPE_VALUES),
                name="support_message_author_type_known",
            ),
        ]

    def __str__(self) -> str:
        flag = " (internal)" if self.is_internal else ""
        return f"{self.ticket.number}: {self.author_type}{flag}"

    @property
    def visible_to_customer(self) -> bool:
        return not self.is_internal


class SupportAttachment(TimestampedModel):
    """A file on a message, stored privately and served only by the download view."""

    message = models.ForeignKey(
        SupportMessage,
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_("message"),
    )
    file = models.FileField(
        _("file"),
        storage=PrivateAttachmentStorage(),
        upload_to="support/%Y/%m",
    )
    original_filename = models.CharField(_("original filename"), max_length=255)
    content_type = models.CharField(_("content type"), max_length=64)
    size = models.PositiveBigIntegerField(_("size in bytes"))
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        verbose_name=_("uploaded by"),
    )

    class Meta:
        verbose_name = _("support attachment")
        verbose_name_plural = _("support attachments")
        ordering = ("-created_at",)
        indexes = [
            models.Index(fields=["message", "created_at"], name="support_attach_msg_idx"),
        ]

    def __str__(self) -> str:
        return self.original_filename


class SupportTicketEvent(models.Model):
    """Append-only audit row for one thing that happened to a ticket."""

    class EventType(models.TextChoices):
        CREATED = "created", _("Ticket created")
        ASSIGNED = "assigned", _("Assigned")
        UNASSIGNED = "unassigned", _("Unassigned")
        STATUS_CHANGED = "status_changed", _("Status changed")
        PRIORITY_CHANGED = "priority_changed", _("Priority changed")
        ESCALATED = "escalated", _("Escalated")
        CUSTOMER_MESSAGE = "customer_message", _("Customer message")
        AGENT_MESSAGE = "agent_message", _("Agent reply")
        INTERNAL_NOTE = "internal_note", _("Internal note")
        ATTACHMENT_ADDED = "attachment_added", _("Attachment added")
        REFERENCE_LINKED = "reference_linked", _("Reference linked")
        NOTIFICATION_SENT = "notification_sent", _("Notification sent")

    ticket = models.ForeignKey(
        SupportTicket,
        on_delete=models.CASCADE,
        related_name="events",
        verbose_name=_("ticket"),
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        verbose_name=_("actor"),
        help_text=_("NULL for system-generated events."),
    )
    event_type = models.CharField(_("event type"), max_length=32, choices=EventType.choices)
    old_value = models.CharField(_("old value"), max_length=200, blank=True)
    new_value = models.CharField(_("new value"), max_length=200, blank=True)
    metadata = models.JSONField(_("metadata"), default=dict, blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = _("support ticket event")
        verbose_name_plural = _("support ticket events")
        ordering = ("created_at", "pk")
        indexes = [
            models.Index(fields=["ticket", "created_at"], name="support_event_ticket_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.ticket.number}: {self.event_type}"
