# Generated by Django 5.2.17 on 2026-10-04 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.catalog.validators
import apps.closet.models.items


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0002_order_loyalty_points_order_promotion_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("purchased", "Purchased")],
                        default="manual",
                        editable=False,
                        help_text="Server-assigned: manual, or a delivered order's physical unit.",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "unit",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        help_text="Which identical unit of the same order line this row is (1, 2, ...).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="unit",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tops", "Tops"),
                            ("bottoms", "Bottoms"),
                            ("outerwear", "Outerwear"),
                            ("dresses", "Dresses"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                        ],
                        max_length=16,
                        verbose_name="category",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="name")),
                ("brand", models.CharField(blank=True, max_length=120, verbose_name="brand")),
                ("color", models.CharField(blank=True, max_length=60, verbose_name="colour")),
                ("size", models.CharField(blank=True, max_length=32, verbose_name="size")),
                ("material", models.CharField(blank=True, max_length=120, verbose_name="material")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_season", "All season"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="season",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                            ("party", "Party"),
                            ("office", "Office"),
                            ("travel", "Travel"),
                            ("streetwear", "Streetwear"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="occasion",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("smart_casual", "Smart casual"),
                            ("classic", "Classic"),
                            ("relaxed", "Relaxed"),
                            ("athletic", "Athletic"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="style",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo for manually added clothing (PNG, JPEG or WebP, within the catalogue image limits). FLASHWEAR pieces use the product's own imagery.",
                        upload_to=apps.closet.models.items.closet_image_upload_to,
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="photo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="PROTECT: which delivered order line this physical unit came from; together with the unit number it is the duplicate guard.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closet_items",
                        to="orders.orderitem",
                        verbose_name="order line",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="CASCADE: a wardrobe is private account data and leaves with the account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closet_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="PROTECT: the FLASHWEAR link; empty for manually added clothing.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closet_items",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "closet item",
                "verbose_name_plural": "closet items",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_season", "All season"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="season",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                            ("party", "Party"),
                            ("office", "Office"),
                            ("travel", "Travel"),
                            ("streetwear", "Streetwear"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="occasion",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("smart_casual", "Smart casual"),
                            ("classic", "Classic"),
                            ("relaxed", "Relaxed"),
                            ("athletic", "Athletic"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="style",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("saved", "Saved"), ("archived", "Archived")],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="CASCADE: outfits are private account data and leave with the account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outfits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "outfit",
                "verbose_name_plural": "outfits",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="OutfitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("outerwear", "Outerwear"),
                            ("dress", "Dress"),
                            ("shoes", "Shoes"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order inside the outfit; the service keeps positions dense.",
                        verbose_name="position",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="note")),
                (
                    "closet_item",
                    models.ForeignKey(
                        help_text="PROTECT: outfits are wardrobe history -- a garment worn by an outfit cannot be hard-deleted; archive it instead.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worn_in",
                        to="closet.closetitem",
                        verbose_name="closet item",
                    ),
                ),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="closet.outfit",
                        verbose_name="outfit",
                    ),
                ),
            ],
            options={
                "verbose_name": "outfit item",
                "verbose_name_plural": "outfit items",
                "ordering": ("position",),
            },
        ),
        migrations.AddIndex(
            model_name="closetitem",
            index=models.Index(fields=["user", "status"], name="closet_item_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="closetitem",
            index=models.Index(fields=["user", "category"], name="closet_item_user_category_idx"),
        ),
        migrations.AddIndex(
            model_name="closetitem",
            index=models.Index(fields=["user", "source"], name="closet_item_user_source_idx"),
        ),
        migrations.AddIndex(
            model_name="closetitem",
            index=models.Index(fields=["user", "-created_at"], name="closet_item_user_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="closetitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_item__isnull", False)),
                fields=("order_item", "unit"),
                name="closet_item_unit_per_order_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="closetitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["manual", "purchased"])),
                name="closet_item_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="closetitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        ["tops", "bottoms", "outerwear", "dresses", "shoes", "accessories"],
                    )
                ),
                name="closet_item_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="closetitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])),
                name="closet_item_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="closetitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__gte", 1)), name="closet_item_unit_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="outfit",
            index=models.Index(fields=["user", "status"], name="outfit_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="outfit",
            index=models.Index(fields=["user", "-updated_at"], name="outfit_user_updated_idx"),
        ),
        migrations.AddConstraint(
            model_name="outfit",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "saved", "archived"])),
                name="outfit_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="outfititem",
            index=models.Index(fields=["outfit", "position"], name="outfit_item_outfit_pos_idx"),
        ),
        migrations.AddConstraint(
            model_name="outfititem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0)), name="outfit_item_position_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="outfititem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["top", "bottom", "outerwear", "dress", "shoes", "accessory"])
                ),
                name="outfit_item_role_valid",
            ),
        ),
    ]
