# Generated by Django 5.2.17 on 2026-10-04 08:48

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
        ("shop", "0004_alter_checkoutsession_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "code",
                    models.CharField(
                        help_text="Normalised (trimmed, upper-cased) by the engine before comparison. Letters, digits, hyphen and underscore only.",
                        max_length=32,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Operator-facing terms; not shown to customers unless a template prints it.",
                        verbose_name="description",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed amount")],
                        max_length=16,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent of the eligible subtotal (max 100) or a fixed currency amount.",
                        max_digits=10,
                        verbose_name="discount value",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="Inclusive window opening, in the active time zone.",
                        verbose_name="starts at",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        help_text="Exclusive window closing, in the active time zone.",
                        verbose_name="ends at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="An inactive promotion is rejected even inside its window.",
                        verbose_name="active",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Global cap across all customers. Blank means unlimited.",
                        null=True,
                        verbose_name="usage limit",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalised under a row lock at consumption time; auditable against the PromotionUsage rows.",
                        verbose_name="used count",
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many times one customer may use it. Blank means unlimited.",
                        null=True,
                        verbose_name="per-user limit",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Eligible subtotal must reach this amount before the code applies.",
                        max_digits=10,
                        verbose_name="minimum order amount",
                    ),
                ),
                (
                    "allow_loyalty_redemption",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to stack this promotion with FLASH Points redemption. Some deep discounts exclude points by policy.",
                        verbose_name="allow loyalty redemption",
                    ),
                ),
            ],
            options={
                "verbose_name": "promotion",
                "verbose_name_plural": "promotions",
                "ordering": ("-starts_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("discount_value__gt", 0)),
                        name="engagement_promotion_value_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_type", "fixed"),
                            ("discount_value__lte", 100),
                            _connector="OR",
                        ),
                        name="engagement_promotion_percent_at_most_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                        name="engagement_promotion_window_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("usage_limit__isnull", True),
                            ("used_count__lte", models.F("usage_limit")),
                            _connector="OR",
                        ),
                        name="engagement_promotion_used_within_limit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("per_user_limit__isnull", True),
                            ("per_user_limit__gt", 0),
                            _connector="OR",
                        ),
                        name="engagement_promotion_per_user_limit_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_order_amount__gte", 0)),
                        name="engagement_promotion_min_order_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Whole points held.", verbose_name="points"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("consumed", "Consumed"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Checkout-only holds: after this moment the sweeper may return the points to the pool. Ignored once the hold is attached to an order.",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        help_text="The checkout that requested the hold.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_reservations",
                        to="shop.checkoutsession",
                        verbose_name="checkout",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set once the hold belongs to a placed order; the sweeper then never touches it -- it is released on cancellation or consumed on payment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_reservations",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "points reservation",
                "verbose_name_plural": "points reservations",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"], name="engagement_points_hold_idx"
                    ),
                    models.Index(fields=["order", "status"], name="engagement_hold_order_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("checkout",),
                        name="engagement_one_active_points_hold_per_checkout",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("points__gt", 0)),
                        name="engagement_points_reservation_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Signed: positive credits the balance, negative debits it.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase_earn", "Purchase earn"),
                            ("bonus", "Bonus"),
                            ("redemption", "Redemption"),
                            ("refund_reversal", "Refund reversal"),
                            ("admin_adjustment", "Admin adjustment"),
                            ("expiration", "Expiration"),
                        ],
                        max_length=24,
                        verbose_name="type",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="What caused this movement, e.g. 'order:FW-20260101-AB12CD34' or 'expiry:42'. Unique with the type, which is what makes awards and redemptions idempotent.",
                        max_length=64,
                        verbose_name="reference",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on earning rows only: the sweeper writes an offsetting EXPIRATION movement after this moment. NULL means the points never expire.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional operator context for adjustments and reversals.",
                        max_length=200,
                        verbose_name="note",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when an order caused the movement.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_transactions",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "points transaction",
                "verbose_name_plural": "points transactions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="engagement_points_user_idx"),
                    models.Index(fields=["expires_at"], name="engagement_points_expiry_idx"),
                    models.Index(fields=["order"], name="engagement_points_order_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reference", "transaction_type"),
                        name="engagement_points_reference_type_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reference", ""), _negated=True),
                        name="engagement_points_reference_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount", 0), _negated=True),
                        name="engagement_points_amount_nonzero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("transaction_type__in", ["purchase_earn", "bonus"]), _negated=True
                            ),
                            ("amount__gt", 0),
                            _connector="OR",
                        ),
                        name="engagement_points_earn_types_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "transaction_type__in",
                                    ["redemption", "refund_reversal", "expiration"],
                                ),
                                _negated=True,
                            ),
                            ("amount__lt", 0),
                            _connector="OR",
                        ),
                        name="engagement_points_spend_types_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the promotion actually took off this order's eligible subtotal.",
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order the discount was granted on; unique per promotion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_usages",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="engagement.promotion",
                        verbose_name="promotion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "promotion usage",
                "verbose_name_plural": "promotion usages",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["promotion", "user"], name="engagement_usage_promo_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promotion", "order"),
                        name="engagement_one_usage_per_promotion_and_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("discount_amount__gt", 0)),
                        name="engagement_promotion_usage_amount_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1 (poor) to 5 (excellent).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="title")),
                (
                    "body",
                    models.TextField(
                        help_text="What the customer thought, in their own words.",
                        verbose_name="review",
                    ),
                ),
                (
                    "verified_purchase",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Server-derived when the review was created from a qualifying paid order. Never writable from a form or API payload.",
                        verbose_name="verified purchase",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("hidden", "Hidden"),
                        ],
                        default="pending",
                        help_text="Pending until a moderator publishes it.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the review first became public.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a moderator last changed the status.",
                        null=True,
                        verbose_name="moderated at",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The paid order that earned this customer the right to review; it is also what the verified-purchase flag was derived from.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="orders.order",
                        verbose_name="qualifying order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="PROTECT: reviews are part of the product's commercial history.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["product", "status"], name="engagement_review_prod_idx"),
                    models.Index(
                        fields=["status", "-created_at"], name="engagement_review_feed_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "product"),
                        name="engagement_one_review_per_user_and_product",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="engagement_review_rating_between_1_and_5",
                    ),
                ],
            },
        ),
    ]
