# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0001_initial"),
        ("orders", "0002_order_loyalty_points_order_promotion_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pointstransaction",
            index=models.Index(
                fields=["transaction_type", "-created_at"], name="engagement_points_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_active", "-starts_at"], name="engagement_promo_active_idx"
            ),
        ),
    ]
