# Generated by Django 5.2.17 on 2026-10-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="FLASHWEAR", max_length=80, verbose_name="site name"),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Fashion Beyond Ordinary.", max_length=140, verbose_name="tagline"
                    ),
                ),
                (
                    "announcement",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to hide the announcement bar.",
                        max_length=200,
                        verbose_name="announcement bar text",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled the storefront shows a maintenance notice.",
                        verbose_name="maintenance mode",
                    ),
                ),
                (
                    "default_seo_title",
                    models.CharField(
                        default="FLASHWEAR | Fashion Beyond Ordinary",
                        max_length=70,
                        verbose_name="default SEO title",
                    ),
                ),
                (
                    "default_seo_description",
                    models.CharField(
                        default="FLASHWEAR is a fashion-tech storefront. Shop the drop, build your outfit and get styled by AI.",
                        max_length=160,
                        verbose_name="default SEO description",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@flashwear.local",
                        max_length=254,
                        verbose_name="support email",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="core_siteconfiguration_singleton"
                    )
                ],
            },
        ),
    ]
