# Generated by Django 5.2.17 on 2026-10-07 12:44

import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.validators


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_productimage_attribution_productimage_license_and_more"),
        ("core", "0002_seed_site_configuration"),
        ("drops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="title")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("starts_at", models.DateTimeField(verbose_name="starts at")),
                ("ends_at", models.DateTimeField(verbose_name="ends at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Campaign must be active and within the date window to display.",
                        verbose_name="active",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/campaigns/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="banner image",
                    ),
                ),
                ("banner_image_url", models.URLField(blank=True, verbose_name="banner image URL")),
                (
                    "banner_alt",
                    models.CharField(blank=True, max_length=200, verbose_name="banner alt text"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
                "ordering": ["-starts_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="EditorialStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("slug", models.SlugField(max_length=150, unique=True, verbose_name="slug")),
                ("subtitle", models.CharField(blank=True, max_length=255, verbose_name="subtitle")),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="Short fashion story narrative.",
                        verbose_name="story content",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/editorial/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="editorial image",
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="editorial image URL")),
                (
                    "image_alt",
                    models.CharField(blank=True, max_length=200, verbose_name="image alt text"),
                ),
                (
                    "primary_cta_text",
                    models.CharField(blank=True, max_length=50, verbose_name="CTA text"),
                ),
                (
                    "primary_cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Relative path (e.g. /catalog/) or full URL.",
                        max_length=255,
                        verbose_name="CTA destination",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="display order"),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="published")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="starts at"),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="ends at")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editorial_stories",
                        to="core.campaign",
                        verbose_name="campaign",
                    ),
                ),
                (
                    "linked_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editorial_stories",
                        to="catalog.category",
                        verbose_name="linked category",
                    ),
                ),
                (
                    "linked_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editorial_stories",
                        to="catalog.collection",
                        verbose_name="linked collection",
                    ),
                ),
                (
                    "linked_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editorial_stories",
                        to="catalog.product",
                        verbose_name="linked products",
                    ),
                ),
            ],
            options={
                "verbose_name": "editorial story",
                "verbose_name_plural": "editorial stories",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("featured_collection", "Featured Collection"),
                            ("new_arrivals", "New Arrivals"),
                            ("editorial", "Editorial Story"),
                            ("shop_by_mood", "Shop by Mood"),
                            ("featured_products", "Featured Products"),
                            ("creator", "Creator / Community"),
                            ("complete_look", "Complete the Look"),
                            ("drops", "Drops"),
                            ("banner", "Promotional Banner"),
                        ],
                        default="featured_products",
                        max_length=40,
                        verbose_name="section type",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subtitle / short description"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Only enabled sections are rendered on the storefront.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear higher on the page.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional scheduled start visibility.",
                        null=True,
                        verbose_name="starts at",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional scheduled end visibility.",
                        null=True,
                        verbose_name="ends at",
                    ),
                ),
                (
                    "desktop_image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/sections/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="desktop image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/sections/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="mobile image",
                    ),
                ),
                (
                    "desktop_image_url",
                    models.URLField(blank=True, verbose_name="desktop image URL"),
                ),
                ("mobile_image_url", models.URLField(blank=True, verbose_name="mobile image URL")),
                (
                    "image_alt",
                    models.CharField(blank=True, max_length=200, verbose_name="image alt text"),
                ),
                (
                    "overlay_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("bottom", "Bottom"),
                        ],
                        default="center",
                        max_length=20,
                        verbose_name="overlay position",
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(blank=True, max_length=50, verbose_name="primary CTA text"),
                ),
                (
                    "primary_cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Relative path (e.g. /catalog/) or full URL.",
                        max_length=255,
                        verbose_name="primary CTA destination",
                    ),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(blank=True, max_length=50, verbose_name="secondary CTA text"),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Relative path (e.g. /drops/) or full URL.",
                        max_length=255,
                        verbose_name="secondary CTA destination",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this section is only visible when the campaign is running.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="core.campaign",
                        verbose_name="seasonal campaign",
                    ),
                ),
                (
                    "linked_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_sections",
                        to="catalog.category",
                        verbose_name="linked category",
                    ),
                ),
                (
                    "linked_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_sections",
                        to="catalog.collection",
                        verbose_name="linked collection",
                    ),
                ),
                (
                    "linked_drop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_sections",
                        to="drops.flashdrop",
                        verbose_name="linked drop",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage section",
                "verbose_name_plural": "homepage sections",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="display order"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="starts at"),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="ends at")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchandised_sections",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_products",
                        to="core.homepagesection",
                        verbose_name="homepage section",
                    ),
                ),
            ],
            options={
                "verbose_name": "section product",
                "verbose_name_plural": "section products",
                "ordering": ["display_order", "id"],
                "unique_together": {("section", "product")},
            },
        ),
    ]
