# Generated by Django 5.2.17 on 2026-10-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "provider",
                    models.CharField(
                        help_text="Which integration took the money, e.g. 'development'.",
                        max_length=32,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The provider's id for this payment; what webhooks are matched on.",
                        max_length=64,
                        verbose_name="provider reference",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="currency")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=32, verbose_name="failure code"),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, max_length=200, verbose_name="failure message"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=32, verbose_name="provider")),
                (
                    "event_id",
                    models.CharField(
                        help_text="Provider-assigned id; the idempotency key.",
                        max_length=64,
                        verbose_name="event id",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=16,
                        verbose_name="event type",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="payload")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment event",
                "verbose_name_plural": "payment events",
                "ordering": ("-received_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="payments_one_event_per_provider_id"
                    )
                ],
            },
        ),
    ]
