# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_orders_order_created_idx_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["-created_at"], name="payments_payment_created_idx"),
        ),
    ]
