# Generated by Django 5.2.17 on 2026-10-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_returnrequest_returnitem_returnevent_and_more"),
        ("payments", "0002_payment_payments_payment_created_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "number",
                    models.CharField(
                        db_index=True,
                        help_text="Public handle: REF-<date>-<random>.",
                        max_length=32,
                        unique=True,
                        verbose_name="refund number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="currency")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("return", "Return"),
                            ("defective", "Defective item"),
                            ("exchange_difference", "Exchange price difference"),
                            ("cancellation", "Order cancellation"),
                            ("goodwill", "Customer goodwill"),
                            ("shipping", "Shipping fee"),
                            ("other", "Other"),
                        ],
                        default="return",
                        max_length=32,
                        verbose_name="reason",
                    ),
                ),
                ("provider", models.CharField(max_length=32, verbose_name="provider")),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The provider's id for this refund.",
                        max_length=64,
                        verbose_name="provider reference",
                    ),
                ),
                (
                    "is_shipping_refunded",
                    models.BooleanField(default=False, verbose_name="shipping refunded"),
                ),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="note")),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=32, verbose_name="failure code"),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, max_length=200, verbose_name="failure message"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="processed at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="orders.returnrequest",
                        verbose_name="return request",
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"], name="payments_re_order_i_9e1c29_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="payments_re_status_3f2058_idx"
                    ),
                ],
            },
        ),
    ]
