# Generated by Django 5.2.17 on 2026-10-03 21:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("shop", "0004_alter_checkoutsession_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "on_hand",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Units physically in the warehouse.",
                        verbose_name="on hand",
                    ),
                ),
                (
                    "reserved",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Units held by active checkout reservations.",
                        verbose_name="reserved",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock level",
                "verbose_name_plural": "stock levels",
                "ordering": ("variant__sku",),
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("adjustment", "Adjustment"),
                            ("reserved", "Reserved"),
                            ("released", "Released"),
                            ("expired", "Hold expired"),
                            ("sold", "Sold"),
                        ],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "on_hand_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Signed change to ``on_hand``; 0 for hold-only movements.",
                        verbose_name="on hand delta",
                    ),
                ),
                (
                    "reserved_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Signed change to ``reserved``; 0 for stock-only movements.",
                        verbose_name="reserved delta",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="What caused this, e.g. 'order:FW-...' or 'reservation:<pk>'.",
                        max_length=64,
                        verbose_name="reference",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The operator behind a manual adjustment, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement",
                "verbose_name_plural": "inventory movements",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Units held.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("consumed", "Consumed"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="After this moment the sweeper may return the hold to the pool.",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="shop.checkoutsession",
                        verbose_name="checkout",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "ordering": ("-created_at",),
            },
        ),
    ]
