# Generated by Django 5.2.17 on 2026-10-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Set once the hold belongs to a placed order; the sweeper never touches it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="orders.order",
                verbose_name="order",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="catalog.productvariant",
                verbose_name="variant",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="variant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock",
                to="catalog.productvariant",
                verbose_name="variant",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["variant", "created_at"], name="inventory_i_variant_b826d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["status", "expires_at"], name="inventory_r_status_8d1db9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["order", "status"], name="inventory_r_order_i_b21025_idx"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("checkout", "variant"),
                name="inventory_one_active_hold_per_checkout_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="inventory_reservation_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("on_hand"))),
                name="inventory_stock_reserved_within_on_hand",
            ),
        ),
    ]
