# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_cat_prod_featured_idx"),
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["-created_at"], name="inventory_movement_created_idx"),
        ),
    ]
