# Generated by Django 5.2.17 on 2026-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventorymovement_inventory_movement_created_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("adjustment", "Adjustment"),
                    ("reserved", "Reserved"),
                    ("released", "Released"),
                    ("expired", "Hold expired"),
                    ("sold", "Sold"),
                    ("returned", "Returned"),
                ],
                max_length=16,
                verbose_name="kind",
            ),
        ),
    ]
