# Generated by Django 5.2.17 on 2026-10-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productimage_attribution_productimage_license_and_more'),
        ('closet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Public-facing name. Blank uses the user's name.", max_length=200, verbose_name='display name')),
                ('slug', models.SlugField(help_text='URL-safe identifier for the creator profile page.', max_length=200, unique=True, verbose_name='slug')),
                ('bio', models.TextField(blank=True, help_text='Public biography displayed on profile.', verbose_name='biography')),
                ('avatar', models.ImageField(blank=True, help_text='Profile image. Recommended: 400x400px.', null=True, upload_to='creators/avatars/', verbose_name='avatar')),
                ('cover_image', models.ImageField(blank=True, help_text='Header image. Recommended: 1200x400px.', null=True, upload_to='creators/covers/', verbose_name='cover image')),
                ('website', models.URLField(blank=True, help_text='Personal or brand website URL.', verbose_name='website')),
                ('instagram_handle', models.CharField(blank=True, max_length=150, verbose_name='Instagram handle')),
                ('tiktok_handle', models.CharField(blank=True, max_length=150, verbose_name='TikTok handle')),
                ('location', models.CharField(blank=True, help_text='Display location only. Not stored publicly beyond this.', max_length=200, verbose_name='location')),
                ('status', models.CharField(choices=[('pending', 'Pending application'), ('approved', 'Approved creator'), ('suspended', 'Suspended'), ('rejected', 'Rejected application')], default='pending', help_text='Derived from application workflow.', max_length=16, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, help_text='Staff-only flag for featured creators.', verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'creator profile',
                'verbose_name_plural': 'creator profiles',
            },
        ),
        migrations.CreateModel(
            name='CreatorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post headline. Shown on profile and discovery pages.', max_length=300, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-safe identifier for the post page.', max_length=300, unique=True, verbose_name='slug')),
                ('caption', models.TextField(blank=True, help_text='Post body text. Supports basic formatting.', verbose_name='caption')),
                ('cover_image', models.ImageField(blank=True, help_text='Primary image for the post. Recommended: 1200x628px.', null=True, upload_to='creator_posts/covers/', verbose_name='cover image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', help_text='Derived from publication + moderation workflow.', max_length=16, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was first published.', null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this post is scheduled to go live.', null=True, verbose_name='scheduled at')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Analytics-ready counter. Incremented via service.', verbose_name='view count')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Analytics-ready counter. Managed via like service.', verbose_name='like count')),
                ('save_count', models.PositiveIntegerField(default=0, help_text='Analytics-ready counter. Managed via save service.', verbose_name='save count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='creator.creatorprofile', verbose_name='creator')),
            ],
            options={
                'verbose_name': 'creator post',
                'verbose_name_plural': 'creator posts',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CreatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_bio', models.TextField(help_text='Free-form text from the applicant about their creator vision.', verbose_name='application biography')),
                ('requested_display_name', models.CharField(help_text='Display name requested by the applicant.', max_length=200, verbose_name='requested display name')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='JSON dict of social platform handles/URLs.', verbose_name='social links')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='portfolio URL')),
                ('status', models.CharField(choices=[('pending', 'Pending application'), ('approved', 'Approved creator'), ('suspended', 'Suspended'), ('rejected', 'Rejected application')], default='pending', max_length=16, verbose_name='status')),
                ('reviewer_note', models.TextField(blank=True, help_text='Internal moderation note. Not shown to applicant on rejection.', verbose_name='reviewer note')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Staff user who performed the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_application_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'creator application',
                'verbose_name_plural': 'creator applications',
                'indexes': [models.Index(fields=['applicant'], name='creator_app_user_idx'), models.Index(fields=['status'], name='creator_app_status_idx'), models.Index(fields=['reviewer'], name='creator_app_reviewer_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='creator.creatorpost', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'creator post like',
                'verbose_name_plural': 'creator post likes',
                'indexes': [models.Index(fields=['user'], name='like_user_idx'), models.Index(fields=['post'], name='like_post_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_like_per_user_post')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Post image. Maximum 10MB. Validated by storage layer.', upload_to='creator_posts/images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alternative text for the image.', max_length=250, verbose_name='alt text')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Determines primary image position.', verbose_name='display order')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark the cover/primary image for the post.', verbose_name='is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='creator.creatorpost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'creator post media',
                'verbose_name_plural': 'creator post media',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['post', 'sort_order'], name='post_media_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'sort_order'), name='unique_post_media_order')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the outfit card.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_post_tags', to='closet.outfit', verbose_name='outfit')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_tags', to='creator.creatorpost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'creator post outfit',
                'verbose_name_plural': 'creator post outfits',
                'indexes': [models.Index(fields=['post'], name='post_outfit_post_idx'), models.Index(fields=['outfit'], name='post_outfit_outfit_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'outfit'), name='unique_post_outfit_tag')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the product card.', verbose_name='display order')),
                ('label', models.CharField(blank=True, help_text="Optional label displayed on the product card, e.g. 'Worn by Creator'.", max_length=128, verbose_name='product label')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='creator.creatorpost', verbose_name='post')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_post_tags', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'creator post product',
                'verbose_name_plural': 'creator post products',
                'indexes': [models.Index(fields=['post'], name='post_product_post_idx'), models.Index(fields=['product'], name='post_product_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'product'), name='unique_post_product_tag')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('misleading', 'Misleading'), ('inappropriate', 'Inappropriate'), ('copyright', 'Copyright'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=16, verbose_name='reason')),
                ('details', models.TextField(blank=True, help_text='Free-form reporter description. Not made public.', verbose_name='details')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('resolved', 'Resolved')], default='new', max_length=16, verbose_name='status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='creator.creatorpost', verbose_name='post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_post_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'creator post report',
                'verbose_name_plural': 'creator post reports',
                'indexes': [models.Index(fields=['post'], name='report_post_idx'), models.Index(fields=['status'], name='report_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post', 'reason'), name='one_report_per_user_post_reason')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='creator.creatorpost', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_post_saves', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'creator post save',
                'verbose_name_plural': 'creator post saves',
                'indexes': [models.Index(fields=['user'], name='save_user_idx'), models.Index(fields=['post'], name='save_post_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_save_per_user_post')],
            },
        ),
        migrations.AddIndex(
            model_name='creatorprofile',
            index=models.Index(fields=['user'], name='creator_user_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorprofile',
            index=models.Index(fields=['status'], name='creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpost',
            index=models.Index(fields=['creator'], name='creator_post_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpost',
            index=models.Index(fields=['status'], name='creator_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpost',
            index=models.Index(fields=['published_at'], name='creator_post_published_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpost',
            index=models.Index(fields=['creator', 'status'], name='creator_post_creat_status_idx'),
        ),
    ]
