# Generated by Django 5.2.17 on 2026-10-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="slug")),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="slug")),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Plain-language copy: what to do and how progress is counted.",
                        verbose_name="description",
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("order_paid", "Paid order"),
                            ("review_written", "Published review"),
                            ("dna_completed", "FLASH DNA complete"),
                            ("closet_add", "Closet item added"),
                            ("outfit_saved", "Outfit saved"),
                            ("wishlist_add", "Wishlist product saved"),
                            ("drop_purchased", "Purchased from a FLASH Drop"),
                            ("creator_post", "Published creator post"),
                            ("loop_resale", "Resale listed"),
                            ("loop_trade_in", "Trade-in accepted"),
                            ("loop_recycle", "Recycling accepted"),
                            ("profile_completed", "Profile completed"),
                        ],
                        help_text="Which server-side handler measures this quest. Immutable in practice: changing it reinterprets every existing row.",
                        max_length=24,
                        verbose_name="quest type",
                    ),
                ),
                (
                    "objective_type",
                    models.CharField(
                        choices=[("count", "Count"), ("boolean", "All-or-nothing")],
                        default="count",
                        max_length=12,
                        verbose_name="objective type",
                    ),
                ),
                (
                    "target",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Units required for COUNT quests. Forced to 1 for BOOLEAN quests.",
                        verbose_name="target",
                    ),
                ),
                (
                    "repeat_period",
                    models.CharField(
                        choices=[
                            ("none", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="none",
                        help_text="NONE counts all-time; the others reset progress on a UTC bucket.",
                        max_length=12,
                        verbose_name="repeat period",
                    ),
                ),
                (
                    "publish_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="publish state",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL means the quest can start as soon as it is published.",
                        null=True,
                        verbose_name="start at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL means the quest stays open indefinitely.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "points_reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="FLASH Points awarded once on completion, through the Phase 7 ledger.",
                        verbose_name="points reward",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first in the quest list.",
                        verbose_name="sort order",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional badge awarded once on completion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_quests",
                        to="quests.badge",
                        verbose_name="badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "quest",
                "verbose_name_plural": "quests",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Quest slug or achievement key that awarded it (audit).",
                        max_length=64,
                        verbose_name="source",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        help_text="PROTECT: a badge with holders can never be deleted out from under them.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holders",
                        to="quests.badge",
                        verbose_name="badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="CASCADE: badges are private account data and leave with the account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user badge",
                "verbose_name_plural": "user badges",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "period_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'' for once-only quests; a UTC bucket for repeatable ones.",
                        max_length=16,
                        verbose_name="period key",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "In progress"), ("completed", "Completed")],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Server-computed, clamped to the quest target. Never client-writable.",
                        verbose_name="progress",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the user explicitly starts the quest; NULL for passive rows.",
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "reward_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The FLASH Points ledger reference issued on completion (audit).",
                        max_length=64,
                        verbose_name="reward reference",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="quests.quest",
                        verbose_name="quest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="CASCADE: quest progress is private account data and leaves with the account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user quest",
                "verbose_name_plural": "user quests",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(
                fields=["publish_state", "sort_order"], name="quest_publish_sort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_at__isnull", True),
                    ("end_at__isnull", True),
                    ("end_at__gt", models.F("start_at")),
                    _connector="OR",
                ),
                name="quest_window_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="quest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("objective_type", "boolean"), ("target__gte", 1), _connector="OR"
                ),
                name="quest_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("objective_type", "boolean"), _negated=True),
                    models.Q(("repeat_period", "none"), ("target", 1)),
                    _connector="OR",
                ),
                name="quest_boolean_is_once_target_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="userbadge_user_badge_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="userquest",
            index=models.Index(fields=["quest", "status"], name="userquest_quest_status_idx"),
        ),
        migrations.AddIndex(
            model_name="userquest",
            index=models.Index(fields=["user", "status"], name="userquest_user_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="userquest",
            constraint=models.UniqueConstraint(
                fields=("user", "quest", "period_key"), name="userquest_user_quest_period_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="userquest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", True), ("status", "active")),
                    models.Q(("completed_at__isnull", False), ("status", "completed")),
                    _connector="OR",
                ),
                name="userquest_completion_consistent",
            ),
        ),
    ]
