# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userquest",
            index=models.Index(
                fields=["status", "-updated_at"], name="userquest_status_updated_idx"
            ),
        ),
    ]
