# Generated by Django 5.2.17 on 2026-10-04 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.support.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("engagement", "0001_initial"),
        ("loop", "0001_initial"),
        ("orders", "0002_order_loyalty_points_order_promotion_code_and_more"),
        ("payments", "0001_initial"),
        ("quests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Server-generated, e.g. FW-2026-000123. Never taken from a payload.",
                        max_length=32,
                        unique=True,
                        verbose_name="ticket number",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="subject")),
                (
                    "description",
                    models.TextField(
                        help_text="Denormalised copy of the first message, for list views.",
                        verbose_name="description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("payment", "Payment"),
                            ("delivery", "Delivery"),
                            ("return", "Return"),
                            ("refund", "Refund"),
                            ("product", "Product"),
                            ("account", "Account"),
                            ("loyalty", "FLASH Points"),
                            ("promotion", "Promotion"),
                            ("flash_dna", "FLASH DNA"),
                            ("flash_closet", "FLASH Closet"),
                            ("creator", "Creator"),
                            ("flash_loop", "FLASH Loop"),
                            ("flash_drop", "FLASH Drop"),
                            ("quest", "Quest"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("waiting_for_customer", "Waiting for customer"),
                            ("waiting_internal", "Waiting on internal team"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("api", "API"),
                            ("system", "System"),
                            ("admin", "Admin"),
                        ],
                        default="web",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="assigned at"),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="first response at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolved at"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="closed at"),
                ),
                (
                    "last_customer_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last customer message at"
                    ),
                ),
                (
                    "last_agent_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last agent message at"
                    ),
                ),
                (
                    "escalation_reason",
                    models.TextField(blank=True, verbose_name="escalation reason"),
                ),
                (
                    "escalation_target",
                    models.CharField(blank=True, max_length=20, verbose_name="escalation target"),
                ),
                (
                    "escalated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="escalated at"),
                ),
                (
                    "creator_post_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bare id, not a foreign key: apps.creator is not installed.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="creator post id",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL: a ticket outlives the account it belongs to, so the transcript stays auditable after anonymisation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "escalated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="escalated by",
                    ),
                ),
                (
                    "loop_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="loop.loopitem",
                        verbose_name="loop item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="quests.quest",
                        verbose_name="quest",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="engagement.review",
                        verbose_name="review",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="orders.shipment",
                        verbose_name="shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "support ticket",
                "verbose_name_plural": "support tickets",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Agent"),
                            ("system", "System"),
                        ],
                        default="customer",
                        max_length=10,
                        verbose_name="author type",
                    ),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Agent-only. Never rendered to, or emailed to, the customer.",
                        verbose_name="internal",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for SYSTEM entries (the platform writing to the transcript).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "support message",
                "verbose_name_plural": "support messages",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="SupportTicketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Ticket created"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("status_changed", "Status changed"),
                            ("priority_changed", "Priority changed"),
                            ("escalated", "Escalated"),
                            ("customer_message", "Customer message"),
                            ("agent_message", "Agent reply"),
                            ("internal_note", "Internal note"),
                            ("attachment_added", "Attachment added"),
                            ("reference_linked", "Reference linked"),
                            ("notification_sent", "Notification sent"),
                        ],
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, max_length=200, verbose_name="old value"),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, max_length=200, verbose_name="new value"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for system-generated events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="support.supportticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "support ticket event",
                "verbose_name_plural": "support ticket events",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "file",
                    models.FileField(
                        storage=apps.support.storage.PrivateAttachmentStorage(),
                        upload_to="support/%Y/%m",
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                ("content_type", models.CharField(max_length=64, verbose_name="content type")),
                ("size", models.PositiveBigIntegerField(verbose_name="size in bytes")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportmessage",
                        verbose_name="message",
                    ),
                ),
            ],
            options={
                "verbose_name": "support attachment",
                "verbose_name_plural": "support attachments",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["message", "created_at"], name="support_attach_msg_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["customer", "-created_at"], name="support_ticket_cust_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["status", "-created_at"], name="support_ticket_status_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["assigned_to", "status"], name="support_ticket_assign_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["category", "status"], name="support_ticket_cat_idx"),
        ),
        migrations.AddConstraint(
            model_name="supportticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "open",
                            "in_progress",
                            "waiting_for_customer",
                            "waiting_internal",
                            "escalated",
                            "resolved",
                            "closed",
                        ),
                    )
                ),
                name="support_ticket_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportticket",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ("low", "normal", "high", "urgent"))),
                name="support_ticket_priority_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("author_type", "customer"), ("is_internal", True), _negated=True
                ),
                name="support_message_customer_not_internal",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("author_type__in", ("customer", "agent", "system"))),
                name="support_message_author_type_known",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticketevent",
            index=models.Index(fields=["ticket", "created_at"], name="support_event_ticket_idx"),
        ),
    ]
