# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_cat_prod_featured_idx"),
        ("engagement", "0002_pointstransaction_engagement_points_type_idx_and_more"),
        ("loop", "0002_loopitem_loop_item_type_created_idx"),
        ("orders", "0003_order_orders_order_created_idx_and_more"),
        ("payments", "0002_payment_payments_payment_created_idx"),
        ("quests", "0002_userquest_userquest_status_updated_idx"),
        ("support", "0002_seed_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["-updated_at"], name="support_ticket_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["priority", "-updated_at"], name="support_ticket_prio_idx"),
        ),
    ]
