# Generated by Django 5.2.17 on 2026-10-05 12:30

import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_alter_brand_logo_alter_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for the drop landing page.",
                        null=True,
                        upload_to="drops/heroes/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="hero image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Derived from publication, start/end time, and cancellation.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this drop becomes purchasable.",
                        null=True,
                        verbose_name="starts at",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this drop stops being purchasable.",
                        null=True,
                        verbose_name="ends at",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this drop first became visible on the storefront.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "flash drop",
                "verbose_name_plural": "flash drops",
                "ordering": ("-starts_at", "-created_at"),
                "indexes": [
                    models.Index(fields=["status", "-starts_at"], name="drop_status_starts_idx"),
                    models.Index(fields=["status", "-ends_at"], name="drop_status_ends_idx"),
                    models.Index(
                        fields=["status", "-published_at"], name="drop_status_published_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DropProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order_position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first on the drop page.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show in featured slots on the drop landing page.",
                        verbose_name="featured",
                    ),
                ),
                (
                    "drop_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label displayed on the product card, e.g. 'Launch Edition'.",
                        max_length=128,
                        verbose_name="drop label",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drop_products",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drop_products",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
                (
                    "drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="drops.flashdrop",
                        verbose_name="drop",
                    ),
                ),
            ],
            options={
                "verbose_name": "drop product",
                "verbose_name_plural": "drop products",
                "ordering": ("order_position", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", False)),
                        fields=("drop", "product", "variant"),
                        name="drop_unique_product_variant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", True)),
                        fields=("drop", "product"),
                        name="drop_unique_product_no_variant",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DropAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_allocated",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Fixed total quantity allocated to this drop. Null = unlimited.",
                        null=True,
                        verbose_name="total allocated",
                    ),
                ),
                (
                    "claimed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many units have been claimed through orders.",
                        verbose_name="claimed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="drops.flashdrop",
                        verbose_name="drop",
                    ),
                ),
            ],
            options={
                "verbose_name": "drop allocation",
                "verbose_name_plural": "drop allocations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("claimed__lte", models.F("total_allocated"))),
                        name="drop_allocation_claimed_within_limit",
                    )
                ],
            },
        ),
    ]
