# Generated by Django 5.2.17 on 2026-10-03 19:50

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_deactivated_at_user_email_verified_at_and_more"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("validated", "Validated"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        help_text="Lifecycle state of this checkout.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "shipping_method_code",
                    models.CharField(
                        blank=True,
                        help_text="Code of the selected shipping method, e.g. 'standard'.",
                        max_length=32,
                        verbose_name="shipping method",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cart subtotal at validation time.",
                        max_digits=10,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Shipping cost at validation time.",
                        max_digits=10,
                        verbose_name="shipping amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal plus shipping at validation time.",
                        max_digits=10,
                        verbose_name="total",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the checkout last passed validation.",
                        null=True,
                        verbose_name="validated at",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Line items, totals and address as they were when validated. Phase 6 builds the order from this.",
                        verbose_name="validated snapshot",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="shop.cart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Delivery address chosen from the customer's address book.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.address",
                        verbose_name="shipping address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "checkout session",
                "verbose_name_plural": "checkout sessions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["user", "status"], name="shop_checkout_user_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("user",),
                        name="shop_checkout_one_open_per_user",
                    )
                ],
            },
        ),
    ]
