# Generated by Django 5.2.17 on 2026-10-03 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_checkoutsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="shop_cart_one_active_per_session",
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "active"), models.Q(("session_key", ""), _negated=True)
                ),
                fields=("session_key",),
                name="shop_cart_one_active_per_session",
            ),
        ),
    ]
