# Generated by Django 5.2.17 on 2026-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_cart_shop_cart_one_active_per_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("validated", "Validated"),
                    ("converted", "Converted to order"),
                    ("abandoned", "Abandoned"),
                ],
                default="open",
                help_text="Lifecycle state of this checkout.",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
