# Generated by Django 5.2.17 on 2026-10-04 08:55

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_checkoutsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="loyalty_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Points the customer chose to redeem. A points reservation pins them while this is set, so a second checkout cannot spend them.",
                verbose_name="FLASH Points",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="promotion_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Normalised promotion code applied to this checkout. The engine re-validates it at every step and again at handoff; this column is the request, not the truth.",
                max_length=32,
                verbose_name="promotion code",
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Subtotal minus discounts plus shipping at validation time.",
                max_digits=10,
                verbose_name="total",
            ),
        ),
    ]
