# Generated by Django 5.2.17 on 2026-10-05 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("product_view", "product view"),
                            ("product_search", "product search"),
                            ("filter_used", "filter used"),
                            ("recommendation_view", "recommendation view"),
                            ("recommendation_click", "recommendation click"),
                            ("cart_add", "cart add"),
                            ("cart_remove", "cart remove"),
                            ("wishlist_add", "wishlist add"),
                            ("wishlist_remove", "wishlist remove"),
                            ("checkout_started", "checkout started"),
                            ("checkout_completed", "checkout completed"),
                            ("purchase", "purchase"),
                            ("drop_view", "drop view"),
                            ("drop_purchase", "drop purchase"),
                            ("creator_content_view", "creator content view"),
                            ("loop_item_view", "loop item view"),
                            ("loop_item_action", "loop item action"),
                            ("quest_view", "quest view"),
                            ("quest_completion", "quest completion"),
                            ("support_ticket_created", "support ticket created"),
                        ],
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="visitor id"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="session key"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="object type"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="object id"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="idempotency key"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "analytics event",
                "verbose_name_plural": "analytics events",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["name", "-created_at"], name="analytics_event_name_created"
                    ),
                    models.Index(
                        fields=["visitor_id", "-created_at"], name="analytics_event_visitor"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="analytics_event_object"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("idempotency_key",),
                        name="analytics_event_one_per_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitorAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(max_length=64, unique=True, verbose_name="visitor id"),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="utm source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="utm medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="utm campaign"
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="utm term"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="utm content"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="referrer"
                    ),
                ),
                (
                    "landing_page",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="landing page"
                    ),
                ),
                (
                    "first_touch_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="first touch at"),
                ),
                (
                    "last_touch_at",
                    models.DateTimeField(auto_now=True, verbose_name="last touch at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "visitor attribution",
                "verbose_name_plural": "visitor attributions",
                "ordering": ("-last_touch_at",),
                "indexes": [
                    models.Index(fields=["user", "-last_touch_at"], name="analytics_attr_user")
                ],
            },
        ),
    ]
