# Generated by Django 5.2.17 on 2026-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                choices=[
                    ("product_view", "product view"),
                    ("product_search", "product search"),
                    ("filter_used", "filter used"),
                    ("recommendation_view", "recommendation view"),
                    ("recommendation_clicked", "recommendation clicked"),
                    ("cart_add", "cart add"),
                    ("cart_remove", "cart remove"),
                    ("wishlist_add", "wishlist add"),
                    ("wishlist_remove", "wishlist remove"),
                    ("checkout_started", "checkout started"),
                    ("checkout_completed", "checkout completed"),
                    ("purchase", "purchase"),
                    ("drop_view", "drop view"),
                    ("drop_purchase", "drop purchase"),
                    ("creator_content_view", "creator content view"),
                    ("loop_item_view", "loop item view"),
                    ("loop_item_action", "loop item action"),
                    ("quest_view", "quest view"),
                    ("quest_completion", "quest completion"),
                    ("support_ticket_created", "support ticket created"),
                    ("outfit_generated", "outfit generated"),
                    ("outfit_saved", "outfit saved"),
                    ("outfit_item_replaced", "outfit item replaced"),
                    ("complete_look_viewed", "complete look viewed"),
                    ("style_goal_selected", "style goal selected"),
                    ("mood_outfit_generated", "mood outfit generated"),
                ],
                max_length=64,
                verbose_name="name",
            ),
        ),
    ]
