# Generated by Django 5.2.17 on 2026-10-03 14:41

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.models.product


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="PNG or WebP with transparency. Optional.",
                        upload_to="catalog/brands/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="http:// or https:// only.",
                        max_length=300,
                        verbose_name="website",
                    ),
                ),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_brand_active_order_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("website_url", ""),
                            ("website_url__regex", "^https?://[^\\s]+$"),
                            _connector="OR",
                        ),
                        name="catalog_brand_website_http_only",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="PNG, JPEG or WebP. Optional.",
                        upload_to="catalog/categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level department.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Wide banner for the collection page and Open Graph. Optional.",
                        upload_to="catalog/collections/",
                        verbose_name="hero image",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="Alternative wide image used on cards and in listings.",
                        upload_to="catalog/collections/",
                        verbose_name="banner image",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on the homepage and in the navigation.",
                        verbose_name="featured",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="starts at"),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="ends at")),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_coll_active_order_idx"
                    ),
                    models.Index(
                        fields=["is_featured", "starts_at"], name="cat_coll_featured_start_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_at__isnull", True),
                            ("ends_at__isnull", True),
                            ("ends_at__gte", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="catalog_collection_window_ordered",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        help_text="Swatch colour only, e.g. #0A1F44. Never used to identify a variant.",
                        max_length=7,
                        verbose_name="hex code",
                    ),
                ),
            ],
            options={
                "verbose_name": "color",
                "verbose_name_plural": "colors",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_color_active_order_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("hex_code__regex", "^#[0-9A-F]{6}$")),
                        name="catalog_color_valid_hex",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Fit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
            ],
            options={
                "verbose_name": "fit",
                "verbose_name_plural": "fits",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_fit_active_order_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_material_active_order_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
            ],
            options={
                "verbose_name": "product tag",
                "verbose_name_plural": "product tags",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cat_tag_active_order_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="name")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="slug")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=300, verbose_name="short description"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Fabric, fit notes, care. Plain text for now; rich text is a later phase.",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Only Active products are visible in the storefront.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Homepage and merchandising slots. A business-critical flag, not a tag.",
                        verbose_name="featured",
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=False,
                        help_text="Shows the New badge and the 'newest' ordering.",
                        verbose_name="new",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped the first time the product goes live. Never cleared.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for an in-house FLASHWEAR product with no external label.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The most specific category. Its parents become the breadcrumb.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="A product can be in as many collections as merchandising needs.",
                        related_name="products",
                        to="catalog.collection",
                        verbose_name="collections",
                    ),
                ),
                (
                    "fit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.fit",
                        verbose_name="fit",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="catalog.material",
                        verbose_name="materials",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="catalog.producttag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("sku", models.CharField(max_length=64, unique=True, verbose_name="SKU")),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="EAN/UPC. Unique when set.",
                        max_length=64,
                        verbose_name="barcode",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="price",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The 'was' price. Must be higher than the price when set.",
                        max_digits=10,
                        null=True,
                        verbose_name="compare at price",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal only. Never shown in the storefront or the public API.",
                        max_digits=10,
                        null=True,
                        verbose_name="cost price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive variants are hidden from the storefront but keep their SKU.",
                        verbose_name="active",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.color",
                        verbose_name="color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product variant",
                "verbose_name_plural": "product variants",
                "ordering": ("product__name", "color__display_order", "size__display_order", "sku"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.models.product.catalog_image_upload_to,
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Describe the image for screen readers and when the image fails to load.",
                        max_length=200,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within the gallery. Lower numbers come first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Used on product cards. Exactly one per product once images exist.",
                        verbose_name="primary image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for colour-specific photography. Leave empty for shared images.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the product/page name. Aim for under 70 characters.",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the short description. Aim for under 160 characters.",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rows stay in the database but disappear from the storefront.",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Compact token used in SKUs, e.g. M, 42, OS.",
                        max_length=32,
                        verbose_name="code",
                    ),
                ),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing (XS-XXL)"),
                            ("numeric", "Numeric (waist, chest)"),
                            ("shoe", "Shoe (EU, UK, US)"),
                            ("one_size", "One size"),
                            ("custom", "Brand-specific"),
                        ],
                        default="clothing",
                        help_text="Which sizing system this code belongs to.",
                        max_length=16,
                        verbose_name="size type",
                    ),
                ),
            ],
            options={
                "verbose_name": "size",
                "verbose_name_plural": "sizes",
                "ordering": ("size_type", "display_order", "code"),
                "indexes": [
                    models.Index(
                        fields=["size_type", "display_order"], name="cat_size_type_order_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("size_type", "code"), name="catalog_size_unique_per_type"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("size_type__in", ["clothing", "numeric", "shoe", "one_size", "custom"])
                        ),
                        name="catalog_size_valid_type",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variants",
                to="catalog.size",
                verbose_name="size",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent", "display_order"], name="cat_cat_parent_order_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "display_order"], name="cat_cat_active_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="catalog_category_not_own_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status", "-published_at"], name="cat_prod_status_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "status"], name="cat_prod_category_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand", "status"], name="cat_prod_brand_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_new", "-created_at"], name="cat_prod_new_created_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="cat_prod_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("published_at__isnull", False),
                    ("status__in", ["draft", "archived"]),
                    _connector="OR",
                ),
                name="catalog_product_live_has_published_at",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "position"], name="cat_image_product_pos_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["variant", "position"], name="cat_image_variant_pos_idx"),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="catalog_image_one_primary_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "is_active"], name="cat_var_product_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="catalog_variant_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gte", models.F("price")),
                    _connector="OR",
                ),
                name="catalog_variant_compare_at_above_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cost_price__isnull", True), ("cost_price__gte", 0), _connector="OR"
                ),
                name="catalog_variant_cost_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="catalog_variant_unique_barcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("color__isnull", False), ("size__isnull", False)),
                fields=("product", "color", "size"),
                name="catalog_variant_unique_color_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("color__isnull", True), ("size__isnull", False)),
                fields=("product", "size"),
                name="catalog_variant_unique_size_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("color__isnull", False), ("size__isnull", True)),
                fields=("product", "color"),
                name="catalog_variant_unique_color_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("color__isnull", True), ("size__isnull", True)),
                fields=("product",),
                name="catalog_variant_unique_default_only",
            ),
        ),
    ]
