# Generated by Django 5.2.17 on 2026-10-05 12:30

from django.db import migrations, models

import apps.catalog.models.product
import apps.catalog.validators


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="PNG or WebP with transparency. Optional.",
                upload_to="catalog/brands/",
                validators=[apps.catalog.validators.validate_catalog_image],
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="PNG, JPEG or WebP. Optional.",
                upload_to="catalog/categories/",
                validators=[apps.catalog.validators.validate_catalog_image],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Alternative wide image used on cards and in listings.",
                upload_to="catalog/collections/",
                validators=[apps.catalog.validators.validate_catalog_image],
                verbose_name="banner image",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Wide banner for the collection page and Open Graph. Optional.",
                upload_to="catalog/collections/",
                validators=[apps.catalog.validators.validate_catalog_image],
                verbose_name="hero image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.catalog.models.product.catalog_image_upload_to,
                validators=[apps.catalog.validators.validate_catalog_image],
                verbose_name="image",
            ),
        ),
    ]
