# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_brand_logo_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "-published_at"], name="cat_prod_featured_idx"
            ),
        ),
    ]
