# Generated by Django 5.2.17 on 2026-10-04 23:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.notifications.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnsubscribeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.notifications.models._generate_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_unsubscribe_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "unsubscribe token",
                "verbose_name_plural": "unsubscribe tokens",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Account created"),
                            ("password_changed", "Password changed"),
                            ("email_changed", "Email changed"),
                            ("login_security", "Login security"),
                            ("order_placed", "Order placed"),
                            ("order_confirmed", "Order confirmed"),
                            ("order_processing", "Order processing"),
                            ("order_shipped", "Order shipped"),
                            ("order_delivered", "Order delivered"),
                            ("order_cancelled", "Order cancelled"),
                            ("payment_pending", "Payment pending"),
                            ("payment_success", "Payment successful"),
                            ("payment_failed", "Payment failed"),
                            ("payment_refunded", "Payment refunded"),
                            ("shipment_created", "Shipment created"),
                            ("shipment_shipped", "Shipment shipped"),
                            ("shipment_delayed", "Shipment delayed"),
                            ("shipment_delivered", "Shipment delivered"),
                            ("support_ticket_created", "Support ticket created"),
                            ("support_agent_reply", "Support agent reply"),
                            ("support_ticket_updated", "Support ticket updated"),
                            ("support_ticket_resolved", "Support ticket resolved"),
                            ("points_earned", "FLASH Points earned"),
                            ("points_redeemed", "FLASH Points redeemed"),
                            ("points_expiring", "FLASH Points expiring"),
                            ("promotion_available", "Promotion available"),
                            ("promotion_expiring", "Promotion expiring"),
                            ("drop_upcoming", "Drop upcoming"),
                            ("drop_live", "Drop live"),
                            ("drop_ended", "Drop ended"),
                            ("creator_application_updated", "Creator application updated"),
                            ("creator_post_moderation", "Creator post moderation"),
                            ("creator_post_featured", "Creator post featured"),
                            ("loop_listing_approved", "Listing approved"),
                            ("loop_listing_rejected", "Listing rejected"),
                            ("trade_in_updated", "Trade-in updated"),
                            ("recycling_updated", "Recycling updated"),
                            ("quest_completed", "Quest completed"),
                            ("quest_reward_granted", "Quest reward granted"),
                            ("badge_earned", "Badge earned"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "Account & security"),
                            ("orders", "Order updates"),
                            ("payments", "Payment updates"),
                            ("delivery", "Delivery updates"),
                            ("support", "Support responses"),
                            ("loyalty", "FLASH Points"),
                            ("promotions", "Promotions"),
                            ("drops", "FLASH Drops"),
                            ("creator", "Creator"),
                            ("loop", "FLASH Loop"),
                            ("quests", "Quests & badges"),
                            ("recommendations", "Recommendations"),
                        ],
                        help_text="Denormalised from the type registry so preference filters never join.",
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In app"), ("email", "Email")],
                        max_length=16,
                        verbose_name="channel",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                        default="normal",
                        max_length=8,
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Future delivery time; the queue sweeper promotes the row when due.",
                        null=True,
                        verbose_name="scheduled for",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                (
                    "failed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="failed at"),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="failure reason"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Channel-sender attempts; doubles as the delivery claim (CAS).",
                        verbose_name="attempts",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Domain noun, e.g. ``order``. Never a raw foreign key.",
                        max_length=32,
                        verbose_name="related object type",
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="related object id"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Site-relative link to the surface this notification points at.",
                        max_length=300,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^/(?!/)[^?\\s]*$",
                                "Action URLs must be site-relative paths like /orders/1/.",
                            )
                        ],
                        verbose_name="action URL",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explicit, non-sensitive template context (order number, totals).",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deterministic business-event key, e.g. order:12:payment_success.",
                        max_length=140,
                        verbose_name="idempotency key",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="notif_user_created_idx"),
                    models.Index(fields=["user", "read_at"], name="notif_user_read_idx"),
                    models.Index(fields=["notification_type"], name="notif_type_idx"),
                    models.Index(fields=["channel", "status"], name="notif_channel_status_idx"),
                    models.Index(fields=["status", "-created_at"], name="notif_status_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("user", "idempotency_key", "channel"),
                        name="notif_user_key_channel_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("action_url__startswith", "//"), _negated=True),
                            models.Q(("action_url__startswith", "http"), _negated=True),
                            models.Q(("action_url__startswith", "mailto:"), _negated=True),
                        ),
                        name="notif_action_url_internal",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "Account & security"),
                            ("orders", "Order updates"),
                            ("payments", "Payment updates"),
                            ("delivery", "Delivery updates"),
                            ("support", "Support responses"),
                            ("loyalty", "FLASH Points"),
                            ("promotions", "Promotions"),
                            ("drops", "FLASH Drops"),
                            ("creator", "Creator"),
                            ("loop", "FLASH Loop"),
                            ("quests", "Quests & badges"),
                            ("recommendations", "Recommendations"),
                        ],
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True, verbose_name="email enabled")),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="in-app enabled"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "ordering": ("category",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"), name="notif_pref_user_category_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Account created"),
                            ("password_changed", "Password changed"),
                            ("email_changed", "Email changed"),
                            ("login_security", "Login security"),
                            ("order_placed", "Order placed"),
                            ("order_confirmed", "Order confirmed"),
                            ("order_processing", "Order processing"),
                            ("order_shipped", "Order shipped"),
                            ("order_delivered", "Order delivered"),
                            ("order_cancelled", "Order cancelled"),
                            ("payment_pending", "Payment pending"),
                            ("payment_success", "Payment successful"),
                            ("payment_failed", "Payment failed"),
                            ("payment_refunded", "Payment refunded"),
                            ("shipment_created", "Shipment created"),
                            ("shipment_shipped", "Shipment shipped"),
                            ("shipment_delayed", "Shipment delayed"),
                            ("shipment_delivered", "Shipment delivered"),
                            ("support_ticket_created", "Support ticket created"),
                            ("support_agent_reply", "Support agent reply"),
                            ("support_ticket_updated", "Support ticket updated"),
                            ("support_ticket_resolved", "Support ticket resolved"),
                            ("points_earned", "FLASH Points earned"),
                            ("points_redeemed", "FLASH Points redeemed"),
                            ("points_expiring", "FLASH Points expiring"),
                            ("promotion_available", "Promotion available"),
                            ("promotion_expiring", "Promotion expiring"),
                            ("drop_upcoming", "Drop upcoming"),
                            ("drop_live", "Drop live"),
                            ("drop_ended", "Drop ended"),
                            ("creator_application_updated", "Creator application updated"),
                            ("creator_post_moderation", "Creator post moderation"),
                            ("creator_post_featured", "Creator post featured"),
                            ("loop_listing_approved", "Listing approved"),
                            ("loop_listing_rejected", "Listing rejected"),
                            ("trade_in_updated", "Trade-in updated"),
                            ("recycling_updated", "Recycling updated"),
                            ("quest_completed", "Quest completed"),
                            ("quest_reward_granted", "Quest reward granted"),
                            ("badge_earned", "Badge earned"),
                        ],
                        max_length=40,
                        verbose_name="topic",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(max_length=32, verbose_name="related object type"),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(verbose_name="related object id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification subscription",
                "verbose_name_plural": "notification subscriptions",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "notification_type",
                            "related_object_type",
                            "related_object_id",
                        ),
                        name="notif_sub_user_topic_uniq",
                    )
                ],
            },
        ),
    ]
