# Generated by Django 5.2.17 on 2026-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'Account & security'), ('orders', 'Order updates'), ('payments', 'Payment updates'), ('delivery', 'Delivery updates'), ('support', 'Support responses'), ('loyalty', 'FLASH Points'), ('promotions', 'Promotions'), ('drops', 'FLASH Drops'), ('creator', 'Creator'), ('loop', 'FLASH Loop'), ('quests', 'Quests & badges'), ('recommendations', 'Recommendations'), ('wishlist', 'Wishlist & stock alerts')], help_text='Denormalised from the type registry so preference filters never join.', max_length=24, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('account_created', 'Account created'), ('password_changed', 'Password changed'), ('email_changed', 'Email changed'), ('login_security', 'Login security'), ('order_placed', 'Order placed'), ('order_confirmed', 'Order confirmed'), ('order_processing', 'Order processing'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('return_requested', 'Return requested'), ('return_approved', 'Return approved'), ('return_rejected', 'Return rejected'), ('return_received', 'Return received'), ('inspection_completed', 'Return inspected'), ('exchange_processed', 'Exchange processed'), ('payment_pending', 'Payment pending'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_refunded', 'Payment refunded'), ('refund_initiated', 'Refund initiated'), ('refund_completed', 'Refund completed'), ('refund_failed', 'Refund failed'), ('shipment_created', 'Shipment created'), ('shipment_shipped', 'Shipment shipped'), ('shipment_delayed', 'Shipment delayed'), ('shipment_delivered', 'Shipment delivered'), ('support_ticket_created', 'Support ticket created'), ('support_agent_reply', 'Support agent reply'), ('support_ticket_updated', 'Support ticket updated'), ('support_ticket_resolved', 'Support ticket resolved'), ('points_earned', 'FLASH Points earned'), ('points_redeemed', 'FLASH Points redeemed'), ('points_expiring', 'FLASH Points expiring'), ('promotion_available', 'Promotion available'), ('promotion_expiring', 'Promotion expiring'), ('drop_upcoming', 'Drop upcoming'), ('drop_live', 'Drop live'), ('drop_ended', 'Drop ended'), ('creator_application_updated', 'Creator application updated'), ('creator_post_moderation', 'Creator post moderation'), ('creator_post_featured', 'Creator post featured'), ('loop_listing_approved', 'Listing approved'), ('loop_listing_rejected', 'Listing rejected'), ('trade_in_updated', 'Trade-in updated'), ('recycling_updated', 'Recycling updated'), ('quest_completed', 'Quest completed'), ('quest_reward_granted', 'Quest reward granted'), ('badge_earned', 'Badge earned'), ('price_drop', 'Price drop alert'), ('back_in_stock', 'Back in stock alert')], db_index=True, max_length=40, verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('account', 'Account & security'), ('orders', 'Order updates'), ('payments', 'Payment updates'), ('delivery', 'Delivery updates'), ('support', 'Support responses'), ('loyalty', 'FLASH Points'), ('promotions', 'Promotions'), ('drops', 'FLASH Drops'), ('creator', 'Creator'), ('loop', 'FLASH Loop'), ('quests', 'Quests & badges'), ('recommendations', 'Recommendations'), ('wishlist', 'Wishlist & stock alerts')], max_length=24, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='notification_type',
            field=models.CharField(choices=[('account_created', 'Account created'), ('password_changed', 'Password changed'), ('email_changed', 'Email changed'), ('login_security', 'Login security'), ('order_placed', 'Order placed'), ('order_confirmed', 'Order confirmed'), ('order_processing', 'Order processing'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('return_requested', 'Return requested'), ('return_approved', 'Return approved'), ('return_rejected', 'Return rejected'), ('return_received', 'Return received'), ('inspection_completed', 'Return inspected'), ('exchange_processed', 'Exchange processed'), ('payment_pending', 'Payment pending'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_refunded', 'Payment refunded'), ('refund_initiated', 'Refund initiated'), ('refund_completed', 'Refund completed'), ('refund_failed', 'Refund failed'), ('shipment_created', 'Shipment created'), ('shipment_shipped', 'Shipment shipped'), ('shipment_delayed', 'Shipment delayed'), ('shipment_delivered', 'Shipment delivered'), ('support_ticket_created', 'Support ticket created'), ('support_agent_reply', 'Support agent reply'), ('support_ticket_updated', 'Support ticket updated'), ('support_ticket_resolved', 'Support ticket resolved'), ('points_earned', 'FLASH Points earned'), ('points_redeemed', 'FLASH Points redeemed'), ('points_expiring', 'FLASH Points expiring'), ('promotion_available', 'Promotion available'), ('promotion_expiring', 'Promotion expiring'), ('drop_upcoming', 'Drop upcoming'), ('drop_live', 'Drop live'), ('drop_ended', 'Drop ended'), ('creator_application_updated', 'Creator application updated'), ('creator_post_moderation', 'Creator post moderation'), ('creator_post_featured', 'Creator post featured'), ('loop_listing_approved', 'Listing approved'), ('loop_listing_rejected', 'Listing rejected'), ('trade_in_updated', 'Trade-in updated'), ('recycling_updated', 'Recycling updated'), ('quest_completed', 'Quest completed'), ('quest_reward_granted', 'Quest reward granted'), ('badge_earned', 'Badge earned'), ('price_drop', 'Price drop alert'), ('back_in_stock', 'Back in stock alert')], max_length=40, verbose_name='topic'),
        ),
    ]
